### ISSUE TITLE
Remove namedropping of publishers

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#1]

**Comment by Bjwebb** [comment]
https://github.com/IATI/IATI-Extra-Documentation/commit/0d3c7cb84b6a1dd72c2fe1a6b861fd3ff9125846 fixed one of these.

**Comment by caprenter** [comment]
Further example here:
http://iatistandard.org/activities-standard/activity-website/

**Comment by Bjwebb** [comment]
Closing this issue, as I think this has now been done.
