### ISSUE TITLE
text / language examples

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#100]
Add to 
- [ ] `collaboration-type`
- [ ] `default-finance-type`
- [ ] `default-flow-type`
- [ ] `default-aid-type`
- [ ] `default-tied-status`

**Comment by stevieflow** [comment]
@bill-anderson 
See code-example for : http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/default-finance-type/

> <default-finance-type code="110" />

Minded to stick with this, rather than try and add xml:lang examples, as we are headed towards language-neutral use of codelists

What do you think?

**Comment by bill-anderson** [comment]
Agree
