### ISSUE TITLE
Link from overview pages to reference pages

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#101]
and vice versa

**Comment by Bjwebb** [comment]
@stevieflow I've created links from the reference pages to the overview pages (e.g. http://dev.iatistandard.org/activity-standard/iati-activities/iati-activity/activity-date/) based on [JSON maping files](https://github.com/IATI/IATI-Extra-Documentation/blob/version-1.04/en/activity-standard/overview-mapping.json), but not the other way round, since you've already included the links. For consistency, should I remove the existing links, and replace them with links generated from the mapping file?

**Comment by stevieflow** [comment]
> For consistency, should I remove the existing links, and replace them with links generated from the mapping file?

Yes please

**Comment by Bjwebb** [comment]
I've now added links from the mapping file - e.g. http://dev.iatistandard.org/activity-standard/overview/classifications/

Remaining TODOs:
- [x] Remove your manually added links, as appropriate
- [x] Change the header level, so that "Reference" isn't in such large letters
- [x] Is "Reference" a useful name for that section?
- [x] @stevieflow Look through the mapping file (or the output on the site) to check it makes sense, and I've not missed anything

**Comment by stevieflow** [comment]
Thanks

I can remove the links in the last clean up - have created a new Issue: https://github.com/IATI/IATI-Extra-Documentation/issues/124

For Reference - I'd suggest "Reference pages"?

Regarding the mapping - that's really great.  Will have to edit this when (for example) any changes are made the overview file name (as in https://github.com/IATI/IATI-Extra-Documentation/issues/114)

**Comment by stevieflow** [comment]
I presume that the Reference links in the side navigation are a result of the (temporary) header level markup?

**Comment by Bjwebb** [comment]
@stevieflow Yes, that's right. Will fix shortly.
