### ISSUE TITLE
Notes and Additional Notes on provider-org and receiver-org

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#102]
These are in the current code-example for `provider-org` and `receiver-org` - a legacy of the copy over from the iatistandard wordpress/wiki:

http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/transaction/provider-org/

> The unique organisation identifier for the provider organisation. Some large organisations already have existing codes assigned through the OECD. For those organisations where no code exists, the organisation can generate their own code for IATI use in the format of [country-registration] - [company-registration number]. (e.g. the organisation identifier for DIPR is: GB-COH-06368740.)
> 
> Additional notes
> 
> Organisation IDs: It is now recommended that organisation ids are built to a convention, so the schema declaration that @ref must be on a codelist is out of date. A change to the schema must occur through our change control process. As such this is flagged for change.

Need to decide if these are to remain in Extra Documentation, as other elements do not include such notes

**Comment by stevieflow** [comment]
@bill-anderson @Bjwebb @caprenter would suggest that this is incorporated into Org ID guidance page , and not in the code-example

**Comment by bill-anderson** [comment]
Agree

**Comment by Bjwebb** [comment]
:+1:

**Comment by stevieflow** [comment]
@caprenter @Bjwebb any chance to take care of this?

Might be best to wait for my changes to be merged by @Bjwebb first...

**Comment by caprenter** [comment]
ok - will remove the 'notes' section from each of these pages:
http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/transaction/provider-org/
http://dev.iatistandard.org/activity-standard/iati-activities/iati-activity/transaction/receiver-org/

and distil the info into:
https://github.com/IATI/IATI-Extra-Documentation/blob/version-1.04/en/FAQs/organisation-identifiers.rst

Links from the reference pages above could be handled by two hops - first to the Organisations overview page http://dev.iatistandard.org/activity-standard/overview/organisations/ and then from there to Org -id info.

**Comment by caprenter** [comment]
On reflection I don't think there is anything in the 'notes' text that is not described in the larger document. So closing this issue.
