### ISSUE TITLE
fss/forecast - example with no value-date

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#103]
For @bill-anderson 

http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/fss/forecast/

current example has a second forecast of:

`<forecast year="2015" currency="GBP">20000</forecast>`

this is missing a `value-date` - is this a mistake?

**Comment by bill-anderson** [comment]
Yes it is a mistake. Must have a value date.

**Comment by stevieflow** [comment]
fixed in https://github.com/IATI/IATI-Extra-Documentation/commit/a3f82813c4bd4a1f0dae073317f7091d44c046a8
