### ISSUE TITLE
location changes - overview

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#104]
Proposal for a page / statement to provide an overview of the key changes between 1.03 and 1.04 for `location`, alongside the changelog

**Comment by Bjwebb** [comment]
Is there information you want to include in this, that isn't already in the changelog at http://dev.iatistandard.org/upgrades/decimal-upgrade-to-1-04/1-04-changes/#activities-schema ?

To avoid duplicating information, I propose making any necessary changes to the changelog, and then linking to it from the location page.

**Comment by stevieflow** [comment]
Thanks

I suppose the _facts_ on what has changed are well documented.  Perhaps what is really needed is better _guidance_ on using `location` in 1.03 / 1.04 - and maybe that is something to task the geocoding working group with, for example?

**Comment by Bjwebb** [comment]
Yes, I think that is a task for the working group. Currently this issue is part of the 1.04 milestone. What specifics tasks need doing for 1.04? Just a link from http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/location/ to the changelog?

**Comment by stevieflow** [comment]
> link from http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/location/ to the changelog?

Yes

**Comment by stevieflow** [comment]
@rolfkleef mentioned that this would be a very useful document to include.

**Comment by stevieflow** [comment]
assigned to @iatisupport as part of June documentation-related tasks

**Comment by wendyrogers** [comment]
I have created a document called Summary Of Changes For Publishers for Location Related Elements In IATI Standard V1.04 here https://docs.google.com/document/d/1I2zoe-_s75kwDKSkU8BRhAZiTy-Fn2FTiaW4BQFUzus/edit for review

**Comment by stevieflow** [comment]
Hi @iatisupport - this is great

I've made some edits - and some coments in terms of making it easier to follow (as in what the two tables are for), but this is a great start.

Would suggest that @bill-anderson proof reads (esp the tables)

We can then work with @Bjwebb to deploy to the site.  Is this a (generic) Guidance doc, or something that is couple with version 1.04?

**Comment by bill-anderson** [comment]
Tables are good. Would be useful to show a fully worked-out 1.03 example and show how it maps in 1.04

**Comment by stevieflow** [comment]
We can provide worked out examples via Example XML files.

The next task is to get this into rst - @Bjwebb any ideas (although it does need a further proof)

Also - I'd imagine that some publishers will want a PDF type version

**Comment by Bjwebb** [comment]
@stevieflow Google Doc -> RST is fairly easy for me to do once it's ready.

Generating PDFs from RST is also possible, and might be something we want to look into more generally https://github.com/IATI/IATI-Standard-SSOT/issues/15

**Comment by stevieflow** [comment]
@Bjwebb within which repo is it best to include this document?

**Comment by stevieflow** [comment]
I've done more editing on https://docs.google.com/document/d/1I2zoe-_s75kwDKSkU8BRhAZiTy-Fn2FTiaW4BQFUzus/edit# and have also included a table comparing the XML 

Suggest that we get this around to some relevant people (eg @rolfkleef and @johnadamsDFID) to check through

**Comment by stevieflow** [comment]
Update: The draft has had more editing and review: https://docs.google.com/document/d/1I2zoe-_s75kwDKSkU8BRhAZiTy-Fn2FTiaW4BQFUzus/edit?disco=AAAAAJpqKps# (this document is also opened for comments btw)

**Comment by stevieflow** [comment]
Update:

All comments resolved in:

https://docs.google.com/document/d/1I2zoe-_s75kwDKSkU8BRhAZiTy-Fn2FTiaW4BQFUzus/edit#

Plus, overview table also at:

https://docs.google.com/spreadsheets/d/1lr1sKwxCKKER4_eDTK254ivAOtpDCqh4k7Ki-y1XZn4/edit#gid=0

@Bjwebb how best to now convert/include this in iatistandard, etc?

**Comment by Bjwebb** [comment]
Just converted it to reStructuredText - https://gist.github.com/Bjwebb/d3c7ed1b9330d9833077 . @stevieflow we should review this together and then push it into the Guidance repository at the appropriate location.

Note that the conversion ended up being a much more manual process than I hoped, because pandoc doesn't support tables very well. If anyone knows a better way of converting google docs with tables to reStructuredText, please do let me know.

**Comment by stevieflow** [comment]
@Bjwebb nice, thanks

Could you also convert : https://docs.google.com/spreadsheets/d/1lr1sKwxCKKER4_eDTK254ivAOtpDCqh4k7Ki-y1XZn4/edit#gid=0 ?

**Comment by Bjwebb** [comment]
@stevieflow That table relies on a lot of formatting (controlling table borders and filling cells with colours) that reStructuredText doesn't directly support. The information needs restructuring, or including in the website some other way (raw html is possible, but I'd rather avoid it). One for us to discuss, I think.

**Comment by stevieflow** [comment]
OK great, thanks.

I'll try and take some formatting out initially

Sent with my thumbs...

**Comment by stevieflow** [comment]
Discussed with @Bjwebb - we can link to the GDoc initially, but will also try and include the table in the main doc

**Comment by stevieflow** [comment]
This is now in dev http://dev.iatistandard.org/upgrades/decimal-upgrade-to-1-04/location-summary/ - to go live Monday 18th Aug
