### ISSUE TITLE
result - examples

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#11]
This needs to be revised, so that a full result example is provided at 

http://dev.iatistandard.org/iati-activities/iati-activity/result.html
- and then this is replicated and highlighted in child pages/elements

**Comment by caprenter** [comment]
Closed via:
https://github.com/IATI/IATI-Extra-Documentation/commit/95b7c483695ca82b3cec23ad4649c15a11fe68e9
