### ISSUE TITLE
Review Comments On Organisation Overview

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Extra-Documentation#112]
http://dev.iatistandard.org/organisation-standard/overview/
- [ ] Is Organisation Standard a name? Should it always be capitalised?
- [x] First and second paras seem to say essentially the same thing. Can they be combined?
- [x] The link from ‘reference’ section goes to a different page from the Reference link in the LH sidebar  and was not what I was expecting (looked more like schema than reference?)

http://dev.iatistandard.org/organisation-standard/overview/organisation-file/
- [x] L1 -  ‘the data that relates to ’ . should be ‘data as described (defined?) by’
- [x] L2 – remove the word ‘all’. 
- [ ] L2 Blank line needs adding after sentence.
- [ ] L3 – Add bullets to list? Blank line needs adding after sentence
- [ ] Consideration Section – remove ‘in the organisation standard’ as this has been described above?
- [ ] What is ‘valid XML’. Might need to qualify?
- [ ] Are point 4 and 5 required as they are details of point 1 (and covered in the publish your datafiles’ section of the Guidance?
- [ ] Should we add that it should be encoded in UTF-8 here?
- [x] Further Guidance might not need link to the Registry if you remove bullet 4 and 5.

http://dev.iatistandard.org/organisation-standard/overview/organisations
Definition
- [ ] L1 ‘organisation’ not ‘organisations’. Also are these organisation ‘types’ or ‘roles’
- [x] Reporting-org – remove the word ‘help’

Considerations
- [ ] Are organisations declared in the standard or in the organisation file?
- [x] Bullet 2 needs rewording as it currently is an extension to bullet 1. Possibly ‘multiple iati-organisation can be described in a single organisation file.’
- [x] Bullet 4 – replace ‘can also’ with ‘should’

http://dev.iatistandard.org/organisation-standard/overview/budgets/
Considerations.
- [ ] Remove both instances of ‘In the organisation standard‘ in L1 and bullet 1 
- [ ] Rather than ‘it is recommended’ can we use ‘should’ or ‘can’ eg Budgets should be forward looking 
- [ ] Bullet 4 – Are budgets only in ‘financial years’. Might there be other budget reporting periods?

http://dev.iatistandard.org/organisation-standard/example-xml/
On the XML example
- [ ] is it correct that the value displayed between the period-start and period-end tags is just the year eg 2014 and no the specified ISO date in full

**Comment by Bjwebb** [comment]
> Rather than ‘it is recommended’ can we use ‘should’ or ‘can’ eg Budgets should be forward looking

We normally use "should" to mean something stronger, and "can" to mean something weaker than "recommended", so I'm not sure whether we should make this change.

**Comment by wendyrogers** [comment]
Yes I agree and I have just picked up the same general point specifically for the Considerations sections as a result of reviewing the IATI Activity Standard Overview

**Comment by stevieflow** [comment]
Thanks @iatisupport 

I've made changes to this, and marked the bullets above accordingly

Some further notes:
- Naming of standard - I took a consistent approach to name it the **IATI organisation standard** - so this should go back to naming conventions for decisions 
- Blank lines on organisation-file page - one to check on the next build

Organisations
I can see your point.  There is an overview page specifically for iati-organisation, and then one for "organisations" as a means to describe other types of orgs that can be used.  The latter duplicates content from the former, it can be argued.  One to review post-1.04 I think: #131
- Considerations section
  I also took the decision to have a consistent line here - about using the standard to describe/declare XYZ- therefore leave this for now, but can review in context of language conventions

Valid XML. Good point: #129

Budgets for financial years - understood.  I suggest we leave this in as a recommendation for now, and review afterwards

XML example: this is discussed in #38

If you can just check this feedback, I think we can then close this Issue

**Comment by wendyrogers** [comment]
Yes have checked the feedback and happy to close
