### ISSUE TITLE
Which elements are not explicitly referenced in the overview pages?

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#113]
- [ ] `legacy-data`
- [x] `conditions`

**Comment by stevieflow** [comment]
@Bjwebb @bill-anderson `legacy-data` is the only element that is now not covered via the overview pages.

This is the reference page: http://iatistandard.org/activity-standard/iati-activities/iati-activity/legacy-data/

Is an overview page needed?

**Comment by bill-anderson** [comment]
I think it does need an explanation beyond the definition (which will improve in 2.01) - and a worked example

**Comment by stevieflow** [comment]
Pushing into the June tidyup milestone therefore

**Comment by stevieflow** [comment]
Closing, as now covered in #160 - getting a code-example up might be the best first step (rather than a whole overview page).

If needed, we can come back to this
