### ISSUE TITLE
CRS-Add - Aid Type Flag - significance

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#116]
@bill-anderson 

http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/crs-add/aidtype-flag/

`significance`:

> Does this flag apply? If ‘false’ do not report the flag

Therefore:

`<aidtype-flag code="1" significance="0" />` should not be reported?

But 

`
<aidtype-flag code="1" significance="1" />
<aidtype-flag code="2" significance="1" />
<aidtype-flag code="3" significance="1" />
`

could be?

I question the purpose of `significance` around the statement "If ‘false’ do not report the flag" - unless it is a specific CRS/FSS guidance?

**Comment by bill-anderson** [comment]
In CRS these four codes are separate columns. And are flagged with 1=Yes. So similar to the way we handle policy markers. Significance = 1 means the flag is set. You do not have to report that the flag is not set.

**Comment by stevieflow** [comment]
Parking into Post 1.04 also - as still think this needs review and possible change (after discussion)

**Comment by bill-anderson** [comment]
By parking you mean leave http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/crs-add/aidtype-flag/ as is?

I'm happy with that.

**Comment by stevieflow** [comment]
@bill-anderson the example at http://iatistandard.org/activity-standard/iati-activities/iati-activity/crs-add/aidtype-flag/ doesn't include that `significance="0"` is an option.  

That seems OK to close this Issue?

**Comment by bill-anderson** [comment]
The guidance says that if significance="0" then the element should not be reported. So it is correct that it isn't included in the example.

So ok to close

**Comment by stevieflow** [comment]
Thanks
