### ISSUE TITLE
Gudance on relation between recipient-country/region & location

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#117]
There is no explicit guidance on when `location` should  be invoked, apart from:

http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/location/

Schema text:

> The sub-national geographical identification of the target locations of an activity

Questions that need clarifying in schema / extra/docs:
- Can `location` be used to describe country/regions?
- If a `location` is used, are `recipient-country` / `recipient-region` also needed in the same ''iati-activity``?

**Comment by bill-anderson** [comment]
recipient-country and/or recipient-region are mandatory, irrespective of use of location.

you can reference a country or region - either to define the scope of the activity, or ,more importantly, to geocode it with coordinates so that it can be represented on a map along with sub-national fixed point activities

**Comment by stevieflow** [comment]
ok thanks

Also - does `activity-scope` have a similar relationship to `location` ?

**Comment by bill-anderson** [comment]
Do you mean that activity scope qualifies the meaning of coordinates? - yes

**Comment by stevieflow** [comment]
@bill-anderson you mean 

inclusion of this in an iati-activity: http://dev.iatistandard.org/activity-standard/iati-activities/iati-activity/activity-scope/ 

would inform what is in this:
http://dev.iatistandard.org/activity-standard/iati-activities/iati-activity/location/ ?

**Comment by bill-anderson** [comment]
I thought so but you are making me doubt myself. If an activity is national or regional in scope and one set of coordinates is given, how do you know what the coordinates represent? recipient-region and recipient-country don't tell you this.

**Comment by stevieflow** [comment]
Thanks

Moving this to Post-1.04 so that it doesn't get in the way of getting 1.04 live.

This could become a part of guidance around implementing location

**Comment by stevieflow** [comment]
Have moved this to Guidance repo: https://github.com/IATI/IATI-Guidance/issues/39
