### ISSUE TITLE
location/description

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#125]
This remains in 1.04 - but it is unclear if it is deprecated or not.

A new element, `activity-description` is in from 1.04

@bill-anderson any chance to clarify?  I can mark up the Extra Documenttion page accordingly as a starter

**Comment by stevieflow** [comment]
The same could be asked of `location/name`

**Comment by bill-anderson** [comment]
description describes the location
activity-description describes the activity taking place at the location

say you have a project taking place in three locations which involves building two schools and a clinic. How do you know what is being built where

**Comment by stevieflow** [comment]
OK thanks @bill-anderson 

Will update the overview around this accordingly
