### ISSUE TITLE
1.04 changes - conditions/.condition

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#126]
Should we have a note here:

http://dev.iatistandard.org/upgrades/decimal-upgrade-to-1-04/1-04-changes/

to state that a lang attribute was added/fixed to condition ?

http://dev.iatistandard.org/activity-standard/iati-activities/iati-activity/conditions/condition/

**Comment by Bjwebb** [comment]
Yes, and also in https://github.com/IATI/IATI-Schemas/blob/version-1.04/CHANGES.txt
