### ISSUE TITLE
Review Comments On Activity Overview

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Extra-Documentation#128]
General
- [x] Can the links to reference either be removed or moved to next level down in the LH side bar as there are currently multiple links to just ‘reference’. Alternatively each reference link should be qualified eg Activity File Reference?
- [x] Not sure what the difference is between the ‘Further Guidance – Reference and reference Sections for most data items as they seem to generally contain the same links so rather confusing? Would it be clearer to have a single section called something like ‘IATI Standard Data Definitions’ ?
- [ ] Really need to standardise on language used for Considerations bullets. Usually ‘are’ , ‘can’ (optional), ‘should’ (optional but recommended)  'must' mandatory etc and leave out extra qualifications such as ‘where possible’ ‘if relevant’  ‘it is recommended’ etc  as all should be implicit . Make all statements as short and specific as possible by removing extra words or phrases unless they are providing value qualification . Use the same sentence construction as much as possible..’  eg for documents
  
  > A title and description can be specified for each document.
  > A publisher should regularly check that document URL links are valid etc.
- [x] The first line under each Considerations heading should be standardised eg
  ‘When using {name of element} the following should be considered:

http://dev.iatistandard.org/activity-standard/overview/
- [x] L2 is saying the same thing as L1?
- [ ] Might be useful to add a description of what the Activity Standard actually is? What it is for?
- [x] ‘Further guidance, examples and details’ of what specifically? Add clarification

http://dev.iatistandard.org/activity-standard/overview/activity-file/
- [x] L1 replace ‘relates to’ with ‘conforms to’?
- [x] Add blank line before title ‘Considerations’
- [ ] It must be valid XML. Should that be IATI XML?
- [ ] Not sure if you need the references to the Registry and publishing on a publishers web  site here (as covered in guidance)?
- [x] Should iati-activity/iati-activity under References be a link or something else?

http://dev.iatistandard.org/activity-standard/overview/iati-identifier/
- [ ] L2 should reporting-org be a hyperlink?
- [x] Add blank lines after L2 and L3
- [x] ‘to declare an iati-identifier, the following should be considered:’ no comma required after iait-identifier
- [x] Further Guidance and Reference section contain the same link to iati-identifer
- [x] Should Organisation identifiers under Further Guidance be a hyperlink?

http://dev.iatistandard.org/activity-standard/overview/dates/
- [x] period-start and ``period-end dates – two ‘’s
- [x] Consideration L1 refers to Organisation not Activity Standard?
- [x] Remove extra lines between Consideration bullets
- [x] Should transaction-date in Reference section be a hyperlink?

http://dev.iatistandard.org/activity-standard/overview/organisations/
- [ ] :
  
  > Should a provider-org or receiver-org within a transaction be the same as thereporting-org it is not expected that they are declared, but recommended.
  
  Does the above therefore just mean that it is recommended to include?

http://dev.iatistandard.org/activity-standard/overview/geography/
- [ ] Under Considerations bullet 1 Country code is in different fonts
- [x] Re 
  
  > If a recipient-country is known, then a recipient-region is not expected.
  > If a recipient-country is not known, then a recipient-region is expected.
  
   Did I see something from Bill about this recommendation being reversed?
- [x]  Remove ‘where possible’ from bullet 8

http://dev.iatistandard.org/activity-standard/overview/classifications/
- [ ] Bullet 4 should there be a link to DAC codelist?
- [x] Bullet 5 under Consideration, vocabulary missing an ‘
- [x] Bullet 7 and`default-tied-status` missing a space

http://dev.iatistandard.org/activity-standard/overview/budgets/
- [x]  Definitions bullet 1 – transaction type in different fonts. Also remove ‘This’
- [x] Para 2 replace ‘clarification around budgets’ to ‘clarification of budgets’. Also add blank line after statement
- [x] Add blank line before considerations
- [x] Bullet 1 – remove where possible (implicit in it is recommended)
- [x] Bullet 4 replace ‘would be’ with ‘are’

http://dev.iatistandard.org/activity-standard/overview/transactions/
- [x] Add blank line before Considerations
- [x] Remove extra lines between bullets
- [x] Bullet 1 – remove ‘It is expected’
- [x] Bullet 3 – replace expected with required
- [x] Bullet 4 – remove ‘possible’ and change ‘ being’ to ‘are’
- [x] Expenditure – Add ‘ and project overheads’
- [x] Incoming funds – remove ‘external’ as an org might fund from their own fund raised sources’
- [x] Bullet 5 – include an example for format for negative amounts. Is it -£3000 or (£3000) or something else?

http://dev.iatistandard.org/activity-standard/overview/result/
- [x] Remove Via sentence?
- [x] Bullet 1 needs reformatting. Mixed fonts and missing reference on results?
- [x] Extra line required before ‘Further Guidance’

Http://dev.iatistandard.org/activity-standard/overview/traceability/
- [x] Remove extra space line between bullets under Considerations

http://dev.iatistandard.org/activity-standard/overview/linked-documents/
- [x] L1 under Defintions would sit better under considerations?
- [x] L2 replace would be with ‘can’
- [x] Add blank line after L2
- [x] Para 4 remove ‘Additionally’ as line contains ‘also’
- [x] ‘linked-date in bullet in wrong font?
- [ ] Bullet 1 under considerations – don’t understand what this is saying?
- [x] Bullet 8 refers to the Organisation not Activity Standard

http://dev.iatistandard.org/activity-standard/overview/crs-fss/
- [x] Add a ‘nil return’ statement. Eg There are currently no specific considerations for this element? So that it doesn’t look like something has been left out

http://dev.iatistandard.org/activity-standard/overview/contact-info/
- [x] L1 contact info is missing hyphen
- [ ] Remove the following fields can be provided (unless this is done for all pages)

**Comment by Bjwebb** [comment]
> Can the links to reference either be removed or moved to next level down in the LH side bar as there are currently multiple links to just ‘reference’. Alternatively each reference link should be qualified eg Activity File Reference?

This is a bug. https://github.com/IATI/IATI-Extra-Documentation/issues/101#issuecomment-42000466 Those multiple links to reference should not appear in the sidebar at all.

> Not sure what the difference is between the ‘Further Guidance – Reference and reference Sections for most data items as they seem to generally contain the same links so rather confusing? Would it be clearer to have a single section called something like ‘IATI Standard Data Definitions’ ?

Yes, this is actual duplication, because we were in the middle of changing from one way of managing these links, to another. Steven's fixed this https://github.com/IATI/IATI-Extra-Documentation/issues/124, so it should be sorted next time I generate the site.

**Comment by stevieflow** [comment]
@iatisupport I certainly agree that we should rationalise and standardise the language.  However:

> The first line under each Considerations heading should be standardised eg
> ‘When using {name of element} the following should be considered:

These overview pages are not specifically about an element, but key things that are described in the standard.

Ill deal with spelling and formatting issues right now - and have raised an issue post 1.04 for the language patterns: #132

**Comment by stevieflow** [comment]
@iatisupport fantastic - thanks for this

Have ticked off all changes applied in https://github.com/IATI/IATI-Extra-Documentation/commit/aac366690d5aa12bb78d31c4970c8f4a7b308c69

I think other issues are dealt with elsewhere - so can close this Issue?

**Comment by Bjwebb** [comment]
> > If a recipient-country is known, then a recipient-region is not expected.
> > If a recipient-country is not known, then a recipient-region is expected.
> 
> Did I see something from Bill about this recommendation being reversed?

Yes, but this is a proposal for 2.01, so we shouldn't update the documentation yet.

**Comment by wendyrogers** [comment]
Ah yes. No problem then to leave it until 2.01 then. Thanks
