### ISSUE TITLE
File "must be valid XML."

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#129]
In 

http://dev.iatistandard.org/activity-standard/overview/activity-file/
http://dev.iatistandard.org/organisation-standard/overview/organisation-file/

@iatisupport raises point in #112 that this needs a better explanation

**Comment by Bjwebb** [comment]
Yes, I think we could word this better. However, the current statement is true, so I would suggest postponing this until after the 1.04 release.

**Comment by stevieflow** [comment]
Agreed

**Comment by stevieflow** [comment]
@Bjwebb any suggestions on what we say here?

That it is "well-formed": https://en.wikipedia.org/wiki/Well-formed_XML_document ?

**Comment by Bjwebb** [comment]
We can say that, but it is also true that it must validate against the relevant schema.

**Comment by stevieflow** [comment]
Added: https://github.com/IATI/IATI-Extra-Documentation/commit/c2b6cd8600a3c29ffc882094053f403f5fe9bb47
