### ISSUE TITLE
recipient-region @vocabulary

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#13]
http://dev.iatistandard.org/iati-activities/iati-activity/recipient-region.html

@vocabulary is not mention in schema description

@vocabulary is then described, but not reference to the actual list:

http://dev.iatistandard.org/codelists/RegionVocabulary.html

**Comment by Bjwebb** [comment]
@vocabulary on http://dev.iatistandard.org/iati-activities/iati-activity/recipient-region.html now says "This value should be on the RegionVocabulary codelist."

Does this fix the bug?

Note that the schema still does not mention it, but we are planning to remove those references from the schema in favour of a separate codelist mapping file, which is used by the single source of truth.

**Comment by stevieflow** [comment]
OK great, thanks
