### ISSUE TITLE
review activity example XML

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#134]
Might be easier to merge the two example files, with more comments markup

**Comment by stevieflow** [comment]
This might be useful

Revert to @Bjwebb in line with discussions on how to better name these files

**Comment by Bjwebb** [comment]
I renamed these files in https://github.com/IATI/IATI-Extra-Documentation/commit/50d0471524064b4e2ca348aa47afd91a9b538d1a
