### ISSUE TITLE
Move Example XML and Overview table

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#141]
Feedback from @bill-anderson & @jonihillman 
- let's move these two from "Reference" back into "Overview"

**Comment by stevieflow** [comment]
:+1:

**Comment by stevieflow** [comment]
One for @bjwebb

**Comment by stevieflow** [comment]
@Bjwebb this is the only Issue that now remains in the Post-1.04 Milestone

**Comment by Bjwebb** [comment]
Do we want them at the beginning or the end of the overview section?

**Comment by stevieflow** [comment]
overview table - beginning

Example XML - end
