### ISSUE TITLE
Update Activity & Org Standard homepages

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#142]
Make it clearer what the Overview and Reference sections are, and what to expect

Relation@ #141

**Comment by stevieflow** [comment]
@Bjwebb what rst formatting would you recommend we deploy to create an "alert" type box on these pages - to briefly describe the two sub-sections?  A table?

**Comment by Bjwebb** [comment]
Not sure what you mean by "alert" type box. One to discuss I think.

**Comment by Bjwebb** [comment]
Alert type boxes are possible, but I don't think it's worth the effort here. Maybe move the contents section (e.g. at the bottom of http://iatistandard.org/activity-standard/) to the top and add your explanatory text in there?
