### ISSUE TITLE
Update the Definition For Version

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Extra-Documentation#143]
The definition for version number on http://iatistandard.org/organisation-standard/iati-organisations/iati-organisation/ needs amending to indicate that the version number if specified should be one of 1.01 1.02 1.03 1.04.

Also is it possible to add links to format definitions of 'xsd:decimal' and 'xsd:dateTime'? I had an XML  file fail on the validator for last-updated-datetime and I wanted to find out what the correct format should be?

**Comment by stevieflow** [comment]
@iatisupport good point about the version number - Ill add that to both org and activity examples

Have created #144 for the other point

**Comment by Bjwebb** [comment]
Note that in 2.01 we are introducing a Version Codelist to enforce the version number - http://support.iatistandard.org/entries/57972186-Version-2-01-Iteration-1-8-Miscellaneous

Prior to this, it's not clear that the version number is required to be one of the above values, but we can certainly add guidance stating that it should be.

**Comment by stevieflow** [comment]
Im going to push this into a new milestone for July (in Guidance repo) - relating to cross-standard guidance/overview issues
