### ISSUE TITLE
country budget-item @percentage

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#146]
http://iatistandard.org/activity-standard/iati-activities/iati-activity/country-budget-items/budget-item/

It is not expected that the `percentage` attribute should sum to 100%.  This isnt clear in the examples given

@bill-anderson please confirm if we should update the example

**Comment by bill-anderson** [comment]
Multiple <budget-item> elements should add up to 100% within the same vocabulary. (Can we check this with @markbrougn?)

What needs changing is

"When multiple budget-item are declared, then the percentage values should sum 100% for the specific iati-activity:"

Should be

"When multiple budget-item elements are declared in a single activity, then, for each vocabulary used, the percentage values should sum 100%"

**Comment by stevieflow** [comment]
Have updated this: https://github.com/IATI/IATI-Extra-Documentation/commit/3898c70868fcf5ac22252c5792a41b12e43ebc2a

I've:

Updated text to 

When multiple `budget-item` elements are declared within a single `country-budget-items` element, then, for each `vocabulary` used, the `percentage` values should sum 100%

Changed code example so that two `budget-item` elements are within a single `country-budget-items` element

@markbrough @bill-anderson is this acceptable?

**Comment by stevieflow** [comment]
Assigning to @bill-anderson

**Comment by markbrough** [comment]
This looks good to me!

**Comment by bill-anderson** [comment]
Ditto
