### ISSUE TITLE
document-link - category type

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#149]
Adjust relevant guidance around the following from @bill-anderson :

'A' type documents should only be reported in the Organisation file if there is a good reason for the document not to be linked to a specific activity.

**Comment by stevieflow** [comment]
@bill-anderson From this, I would understand that B type documents are not advised in the Org file?

**Comment by bill-anderson** [comment]
Correct. A and B were originally conceived as differentiating between agency and activity (so you could have an A and B code describing the same type of document - just at a different level of focus)
