### ISSUE TITLE
Note on hierarchies

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#150]
Use this article 

http://support.iatistandard.org/entries/40759343-General-rules-for-multi-level-reporting

(as noted by @iatisupport support in https://github.com/IATI/IATI-Guidance/issues/4#issuecomment-43346998

**Comment by Bjwebb** [comment]
Note that article is a proposal for the 2.01 Upgrade, and not necessarily current guidance.

**Comment by stevieflow** [comment]
Closing this in Extra-Docs - but adding into relevant Issue(s) in Guidance
