### ISSUE TITLE
Standard Ruleset overview table

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#156]
Page that publishes this: https://gist.github.com/Bjwebb/9952268

**Comment by Bjwebb** [comment]
Note that a similar page already exists, but is not linked to: http://iatistandard.org/ruleset/

**Comment by stevieflow** [comment]
Ah OK  - Im just putting in a couple of Issues to build upon it.  Would we want to have this as a main section?

**Comment by stevieflow** [comment]
I have this via https://github.com/IATI/IATI-Extra-Documentation/pull/207 

@Bjwebb may advise on a better way to include this however (as it is currently a copy and paste)

**Comment by Bjwebb** [comment]
I've implemented my better way to include this. http://dev.iatistandard.org/rulesets/standard-ruleset/
