### ISSUE TITLE
Description of rules

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#157]
Page(s) that provide plain English for each Standard rule - and link through to relevant overview / reference page

**Comment by stevieflow** [comment]
@Bjwebb would you be able to create a page into this repository from this: https://gist.github.com/Bjwebb/9952268 ?

**Comment by stevieflow** [comment]
Hold on - this seems to be a duplicate of #156

**Comment by stevieflow** [comment]
This is partly in place via https://github.com/IATI/IATI-Extra-Documentation/pull/207

In discussion with @Bjwebb we agreed not to create a page for every single know rule type just yet - as this may not be clear

Moving to future milestone

**Comment by amy-silcock** [comment]
No further discussion has happened.
