### ISSUE TITLE
Overview page: Rulesets

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#158]
Intro to rulesets and their role

**Comment by stevieflow** [comment]
@Bjwebb Im doing this - but wanted to ask if Rulesets would have their own "section" too?

**Comment by Bjwebb** [comment]
I think they probably should, but I'm happy to be convinced otherwise.

**Comment by stevieflow** [comment]
In the overview section, I'll talk about them (for now) within the page for schema - in terms of a means to "validate" data.  Perhaps we could nest schema and rules within the same section, although a bad knock-on could be change of URLs (not a good idea)

**Comment by Bjwebb** [comment]
Sphinx will let you nest sections in the navigation, but not in terms of urls, btw. We already make use of this in fact: http://iatistandard.org/activity-standard/iati-activities/ has Reference in the navigation but not in the url.

If we have a section about validating data, should it contain something about validating against codelists?

**Comment by stevieflow** [comment]
https://github.com/IATI/IATI-Extra-Documentation/pull/207
