### ISSUE TITLE
reporting-org rules

### ISSUE THREAD

**Issue by bill-anderson** [IATI/IATI-Extra-Documentation#16]
Modify guidance of reporting-org within a single file and its relationship to registry publisher record

**Comment by stevieflow** [comment]
@bill-anderson 

Is the recommendation that `reporting-org` should always be the "iati-identifier" reference that is used in the publisher record on the IATI Registry?

In need of clarification around this is that in the Org Standard there is a specific `iati-identifier` field, which is an org reference.  Hence, it can be possible to have:
- `reporting-org` = 123
- registry id = 123
- `iati-identifier` = ABC

In turn, this might be compounded by the `secondary-publisher` attribute.

## Action

This strikes me as non-1.04 related, as it talks about an instance of software (IATI Registry) that isnt - strictly speaking - a part of the version-controlled standard.... 

Proposal to move issue to Post 1.04

**Comment by bill-anderson** [comment]
I'm happy to push post 1.04 - perhaps to 2.01 to make absolutely clear.

Put org standard aside - there is a separate proposal somewhere arguing we should rename for clarity.

For activities.

1) Registry validation ( how it should work)

When a publisher (registry publisher-id = ABC) registers any packet, ALL activities in the packet MUST contain a reporting-org/@ref that matches the registry IATI identifier. This guarantees that only a user securely logged in with legitimate access to the registry publisher record can publish activities with that publisher's reporting-org/@ref.

2) Activity validation

Looking at an isolated activity on its own it is impossible to prove who published it. We can do two things:
a. Is it a well-formed org-id. At the moment all we can do (2.01) is validate that the prefix matches our code list
b. Is it in the list of registry iati-identifiers? All this tells us is that some publisher has registered this iati identifier (not that the activity was actually published by that publisher). 

The registry validation is the key to the security of ids. Our own validation is (currently) secondary

**Comment by caprenter** [comment]
@bill-anderson Just a nudge on this. What is the action to resolve this now please?

**Comment by stevieflow** [comment]
@bill-anderson we have clarified that this is not the case with the current Registry.  Is this a proposal to add such rule/functionality to it?

> 1) Registry validation ( how it should work)
> 
> When a publisher (registry publisher-id = ABC) registers any packet, ALL activities in the packet MUST contain a reporting-org/@ref that matches the registry IATI identifier. This guarantees that only a user securely logged in with legitimate access to the registry publisher record can publish activities with that publisher's reporting-org/@ref.

**Comment by bill-anderson** [comment]
Spot on

**Comment by stevieflow** [comment]
@bill-anderson I dont understand you.  You want this functionality built into the IATI CKAN?

**Comment by bill-anderson** [comment]
Nope, the next generation

**Comment by stevieflow** [comment]
The action on this Issue is not really defined.  Pushing to "future"

**Comment by amy-silcock** [comment]
No further comments since 2014. V2 guidance can be found here: http://reference.iatistandard.org/203/activity-standard/summary-table/
