### ISSUE TITLE
code-example for legacy-data

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#160]
@bill-anderson what would make a meaningful example for `legacy-data`?

Only two publishers currently use it: http://dashboard.iatistandard.org/element/iati-activity_legacy-data_@iati-equivalent.html

Only one of those (DFID) use the `iati-equivalent` attribute:

`<legacy-data name="14010 Water Resources Policy and Administrative Management, (MDG Water and Sanitation)" value="14010" iati-equivalent="sector"/>`

An example @Bjwebb drafted:

`<legacy-data name="status" value="22" iati-equivalent="activity-status" />`

**Comment by Bjwebb** [comment]
It's worth pointing out that I think DFID's usage is incorrect - http://data.tickets.iatistandard.org/ticket/195

**Comment by bill-anderson** [comment]
@name should be the name of the field in their legacy system - not the name of the value

**Comment by bill-anderson** [comment]
@Bjwebb example is good

in DFID's case ...

``` xml
 <legacy-data name="CRS Sector Code" value="14010" iati-equivalent="sector"/>
 <legacy-data name="CRS Sector Description" value="14010 Water Resources Policy and Administrative Management, (MDG Water and Sanitation" iati-equivalent="sector"/>
```

**Comment by stevieflow** [comment]
@bill-anderson @Bjwebb is `sector` a good example for `legacy-data` though ?  Because - the IATI sector defaults to CRS Sector anyway..?

**Comment by bill-anderson** [comment]
Agree it looks confusing. The name should in fact be "CRS Sector Code (incl. Legacy values)". The reason for DFID using it is that some of their older projects use codes that no longer exist (because CRS does not understand deprecation and deletes codes that are still in use.)

**Comment by stevieflow** [comment]
Thanks

@bill-anderson in the above example, would it therefore be expected that a `legacy-data` element is published for all `sector` values within that `iati-activity`, or just those that are no longer on the DAC list?

**Comment by bill-anderson** [comment]
I would recommend only when required. I think DFID does it for all which is confusing. They should have logic which says: if sector code not in current code list then recalculate sector code and add legacy data

**Comment by stevieflow** [comment]
Have created an initial code-example for this: https://github.com/IATI/IATI-Extra-Documentation/commit/291dab268edac12aa23a7ada836cb129d3cbb64a

Have pushed Guidance on this into: https://github.com/IATI/IATI-Guidance/issues/21

**Comment by johnadamsDFID** [comment]
Thanks all for the helpful examples etc. This is much useful, although low priority for now.
