### ISSUE TITLE
Review: Schema page - intro text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#162]
@Bjwebb where is this text managed?

> The IATI standard consists of a number of schema, the main ones being Organisation and Activity, supplemented by the Registry Record which provides a common format for the reporting of metadata to the IATI Registry.

(via http://iatistandard.org/schema/)

It might be useful to review this

**Comment by stevieflow** [comment]
Ah sorry - it's here: https://github.com/IATI/IATI-Extra-Documentation/blob/version-1.04/en/schema.rst !

**Comment by stevieflow** [comment]
@Bjwebb @caprenter I've made an attempt to update this page (it has not really changed in the past years).

Whilst I havent removed anything, I would appreciate any feedback:

https://github.com/IATI/IATI-Extra-Documentation/blob/4a6b43d5967f2d7cd6a63b0d2e5d2eee2e964ee0/en/schema.rst

Also - is it possible / advisable / useful for us to provide a zipped download of all schema (and CHANGES.txt)?

**Comment by Bjwebb** [comment]
Like https://github.com/IATI/IATI-Schemas/archive/v1.04.zip ?

**Comment by stevieflow** [comment]
Yes - although this contains more files than listed on /schema - should we also update /schema accordingly?

**Comment by Bjwebb** [comment]
Possibly. Also worth considering whether https://github.com/IATI/IATI-Schemas/blob/version-1.04/README.txt needs updating.

**Comment by stevieflow** [comment]
Closing this, as page is updated and #201 deals with other items
