### ISSUE TITLE
IATIStandard homepage

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#166]
Consider how some of the overview text can in fact help shape the homepage

**Comment by stevieflow** [comment]
@Bjwebb where is the content for the iatistandard homepage administered?

**Comment by Bjwebb** [comment]
https://github.com/IATI/IATI-Websites/blob/master/iatistandard/_templates/layout_base.html#L207
https://github.com/IATI/IATI-Websites/blob/master/iatistandard/_templates/layout_base.html#L252

**Comment by stevieflow** [comment]
moving to future iteration

**Comment by amy-silcock** [comment]
No further discussion has happened.
