### ISSUE TITLE
Review dates and text on Org budgets

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#167]
eg example-code on: 

http://iatistandard.org/organisation-standard/iati-organisations/iati-organisation/total-budget/

@bill-anderson 
- The `value-date` should always be in the past?  And - when presenting three budgets, we'd expect that this would be the same date?
- Do we need better text examples - whereby people can annotate ?

**Comment by stevieflow** [comment]
@bill-anderson

**Comment by bill-anderson** [comment]
The value-date should always be in the past? 
Yes

And - when presenting three budgets, we'd expect that this would be the same date?
Not necessarily

Do we need better text examples - whereby people can annotate ?
Not sure what you mean. I would take out /text()

**Comment by stevieflow** [comment]
Thanks - made sure all value-dates are in the past, and removed /text() from examples 

Added line to both activity and org budget overview pages about value-date in the "past"

 in https://github.com/IATI/IATI-Extra-Documentation/commit/cdbd93f9534ea78fb3399be7e0273c008bcde76a
