### ISSUE TITLE
Make intention of language element clearer

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#169]
http://iatistandard.org/activity-standard/iati-activities/iati-activity/document-link/language/ - state clearly that this is about the language of the document (rather than any string in the XML)

**Comment by Bjwebb** [comment]
Not entirely relevant, but the schema definition for this element is improved in 2.01: https://github.com/IATI/IATI-Schemas/blob/version-2.01/iati-common.xsd#L178

**Comment by stevieflow** [comment]
Also fix: the xm;lang for fr is missing from the code example for `title`: http://iatistandard.org/activity-standard/iati-activities/iati-activity/document-link/

**Comment by stevieflow** [comment]
Also: update overview pages to state that multiple titles for the same doc can be presented, regardless of the destination document language (!)

**Comment by stevieflow** [comment]
fixed in https://github.com/IATI/IATI-Extra-Documentation/commit/fa0c607584424b59c8d4a88361df57e08b9989ce
