### ISSUE TITLE
Administrative Codelists Levels 1 & 2 Still State They Will Be Reviewed For V1.03

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Extra-Documentation#17]
The two Administrative Codelists levels 1 and 2 still state that they are being reviewed for version 1.03

http://iatistandard.org/codelists/administrative_area_1/
http://iatistandard.org/codelists/administrative_area_2/

The codelists are currently not present in dev.iatistandard.org?

NB The actual content/changes for these lists is being managed at http://support.iatistandard.org/entries/30855656-Changes-to-Location-Administrative-element

**Comment by bill-anderson** [comment]
I am happy for them not to be in dev.iatistandard.org.
I don't see the point of including them and then deprecating them on 7 May.

**Comment by stevieflow** [comment]
This seems to be the case for 1.04 - so can be closed @Bjwebb ?
