### ISSUE TITLE
Ensure documentation is updated to say that xsd:date/xsd:datetime is required

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#171]
http://support.iatistandard.org/entries/77542148-Date-and-DateTime-formats

**Comment by Bjwebb** [comment]
As part of this, we need to ensure that we have a sufficiently good description of what xsd:date and xsd:dateTime are.

**Comment by stevieflow** [comment]
Does/could this also apply to 1.04 documentation @Bjwebb ?

**Comment by Bjwebb** [comment]
In 1.04 it is not clear. I would stick to doing this for 2.01

**Comment by stevieflow** [comment]
This is done throughout code-examples.

The Overview page will need to be updated

**Comment by stevieflow** [comment]
This is in the dates overview page
