### ISSUE TITLE
Activity Standard: Definition

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Extra-Documentation#176]
http://iatistandard.org/activity-standard/

Suggest changing third paragraph

> Organisations publish this data in an activity file. It is expected that every organisation publishing IATI data should include one actvity file, which is updated at least annually.

 to say "It is expected that every organisation publishing IATI data should include AT LEAST ONE activity file."

**Comment by stevieflow** [comment]
Have done so.  For now, Ive removed the text around updated at least annually, as we need more robust guidance on this.
