### ISSUE TITLE
Activity Standard: Considerations

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Extra-Documentation#177]
http://iatistandard.org/activity-standard/

Bullet point one, name description and identifier all link to same place, which is fine, but perhaps just include a link at the end to make it less complicated

> What is the name, description and identifier of the activity?

**Comment by Bjwebb** [comment]
"name, description" and "identifier" link to two different places.

**Comment by stevieflow** [comment]
Ive split these into different lines.  Also - done the same for the Org section
