### ISSUE TITLE
Transactions (from Google Doc)

### ISSUE THREAD

**Issue by jonihillman** [IATI/IATI-Extra-Documentation#18]
https://github.com/IATI/IATI-Extra-Documentation/blob/master/en/iati-activities/iati-activity/transaction.rst

Topic: Transactions
Overview
Transactions are the building blocks of IATI. They detail the flow of money between organisations. 
Description
There are four different types of transaction:
Commitment - the total agreed budget for the activity.
Disbursement - the amount transferred to another organisation in the aid delivery chain (e.g. a partner organisation that you fund).
Expenditure - the outlay on goods and services.
Incoming funds - the funds received from an external funding source (e.g. a donor).
What is mandatory?
Transactions should always have a date
Transactions should always have a value - which has to be a whole number (no decimals or commas)
A value date should also be included - as this helps people convert to other currencies.  This value date cannot be in the future
A transaction must have a type (see above description)
Things to consider
- Transactions should be in the past
  More info - 
  Things people ask us: What’s the difference between the transaction types?

**Comment by stevieflow** [comment]
Commit parts of this text to Overview section

Some parts (whole numbers) are no out of date
