### ISSUE TITLE
Activity Standard/Overview/Activity Dates 

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Extra-Documentation#180]
http://iatistandard.org/activity-standard/overview/dates/

The definition section is unclear, suggest numbering or bulleting 

> Those that relate to the iati-activity implementation
>  and 
> a time sensitive...

**Comment by stevieflow** [comment]
Yes.  Have tried to rephrase: https://github.com/IATI/IATI-Extra-Documentation/commit/340590882918c66749e6325b5d49dcbc12b4f16c
