### ISSUE TITLE
Activity Standard/Overview/Result

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Extra-Documentation#181]
http://iatistandard.org/activity-standard/overview/result/

In the definition suggest the bullet point is changed to say 

> a measurable result of a project/activity 
> not just 
> aid

**Comment by Bjwebb** [comment]
Note that this sentence is based on the [definition in the schema](https://github.com/IATI/IATI-Schemas/blob/version-1.04/iati-activities-schema.xsd#L1309).

The schema definition is [being changed in 2.01](https://github.com/IATI/IATI-Schemas/blob/bd94fa88d5bcbce53463bfcca36e5a0b603b1081/iati-activities-schema.xsd#L1695) to read:

> A container for reporting outputs, outcomes, impacts and other results that stem directly from the activity. This may be repeated for each type of result reported.

This should probably form the basis of an updated overview page.

**Comment by stevieflow** [comment]
thanks - have changed to
- `result` - a container for reporting outputs, outcomes, impacts and other results that stem directly from the `iati-activity`.
