### ISSUE TITLE
Activity Standard/Overview/Related Documents

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Extra-Documentation#182]
http://iatistandard.org/activity-standard/overview/linked-documents/

Bullet point 8 of the considerations, unless i've misunderstood the codelist, for the activity standard, the prefix should be A and not B. 

> For document category in the IATI activity standard, it is expected that the DocumentCategory code would be have the B prefix.

**Comment by stevieflow** [comment]
Good spot.  Thanks @izzirbucknall
