### ISSUE TITLE
Activity Standard/Overview/CRS and FSS

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Extra-Documentation#183]
http://iatistandard.org/activity-standard/overview/crs-fss/

Suggest including 
a) examples of the kind of extra information that is being referred to

> crs-add - additional items specific to CRS++ reporting.

b) perhaps a disclaimer at the top about the fact this is only relevant to organisations that report CRs and FSS

**Comment by stevieflow** [comment]
Have added

Please note there is an outstanding Issue (#115) for @bill-anderson in relation to this page
