### ISSUE TITLE
Activity Standard/Overview/Conditions - Wrong Title

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Extra-Documentation#184]
This section is wrongly titled in both the side bar and the top of the web page as 

> Activity Dates
> and should be called 
> conditions

http://iatistandard.org/activity-standard/overview/conditions/

**Comment by stevieflow** [comment]
Good spot: https://github.com/IATI/IATI-Extra-Documentation/commit/215a2bea4c10a0c7466adf9692e56fc777fded9b
