### ISSUE TITLE
Activity Standard/Overview/Conditions - include "human" definition

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Extra-Documentation#185]
It might be useful to define what "conditions" means. Though it is easily understandable to organisations who use conditions, those who don't might be confused by it. 

http://iatistandard.org/activity-standard/overview/conditions/

**Comment by stevieflow** [comment]
I'd agree - although there is no description within the schema itself, as far as I know

This might be more a Guidance issue than Extra-Docs, so closing this for now , with https://github.com/IATI/IATI-Guidance/issues/115 the issue to work on

**Comment by Bjwebb** [comment]
Note that in 2.01 the [schema definition](https://github.com/IATI/IATI-Schemas/blob/version-2.01/iati-activities-schema.xsd) becomes:

```
    Specific terms and conditions attached to the activity that,
    if not met, may influence the delivery of commitments made by
    participating organisations.
```

Which is still not much of a description, but is more than what is there currently.
