### ISSUE TITLE
Codelists - include links to other providers of codelists

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Extra-Documentation#188]
Last paragraph in introductory section, would be good to link through to ISO, DAC CRS etc.

http://iatistandard.org/codelists/

> The codes use existing authority lists where possible and build on codes published by the ISO, OECD DAC, COFOG and Guidestar.

**Comment by stevieflow** [comment]
I've removed this from the specific text on this page - as it is not entirely relevant, nor up to date

However - @bjwebb - would we want to maintain an auto-generated page that lists each codelist plus the embedded status, and which element is applicable (like the Overview tables for the standards)?

**Comment by Bjwebb** [comment]
@stevieflow We can do.
