### ISSUE TITLE
Codelists/Codelist Management

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Extra-Documentation#189]
Paragraph starting "a summary of all changes" - is there somewhere to link to where the sumary of changes will be posted? Or to the github repository? Recommend including those links

http://iatistandard.org/codelists/codelist-management/

> A summary of all changes to all non-emebedded codelists will be published on the IATI Standard website. They can also be found via the list of commits to the GitHub repository.

**Comment by Bjwebb** [comment]
I think the summary of changes is currently missing, and needs to be added (and then linked to).

I think the relevant link for the GitHub repository links is https://github.com/IATI/IATI-Codelists-NonEmbedded/commits/master

**Comment by stevieflow** [comment]
@iatisupport might be interested in this - re: changelog

**Comment by Bjwebb** [comment]
I've added and linked to a changelog in dev, but it's currently lacking in terms of explanation.

@stevieflow Could you write some text for this https://github.com/IATI/IATI-Guidance/blob/master/en/upgrades/nonembedded-codelist-changelog.rst

**Comment by stevieflow** [comment]
Done that.  Also note that @Bjwebb has updated https://github.com/IATI/IATI-Extra-Documentation/blob/version-1.04/en/codelists/codelist-management.rst with a link
