### ISSUE TITLE
An IATI File (from Google Doc)

### ISSUE THREAD

**Issue by jonihillman** [IATI/IATI-Extra-Documentation#19]
Topic: An IATI File
Overview: A file containing one organisation’s IATI xml data
Description: This is simply the name for an electronic file containing information about activities in IATI format
What is mandatory?: n/a
Things to consider: This is not a field, it is the collection of all the organisation’s activities in one place.  
More info: Most organisations will publish one file, containing various activities
Things people ask us: What is an IATI file?

**Comment by stevieflow** [comment]
covered through overview and getting started
