### ISSUE TITLE
Elaborate/clarify the labels Current and New

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#191]
Split out from https://github.com/IATI/IATI-Codelists/issues/38

**Comment by stevieflow** [comment]
@Bjwebb Would this be on the general Codelist page?  And / or - would it be listed in the overview pages mentioned in https://github.com/IATI/IATI-Extra-Documentation/issues/188#issuecomment-50328124 ?

**Comment by Bjwebb** [comment]
We now use CLv1/CLv2/CLv3 (now Current/New), and these link to the codelist API page. David's got a commit in dev that explains what these are. With this, I think this issue can be closed.
