### ISSUE TITLE
Example XML for version 2.01

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#193]
- [x] Org Standard
- [x] Activity Standard

**Comment by Bjwebb** [comment]
[David has fixed](https://github.com/IATI/IATI-Extra-Documentation/commit/a6c0981a9e40f19220c50e8ed2083a6277b938ef) `activity-standard-example-annotated.xml`, but note that `activity-standard-example-annotated-multi.xml` and `organisation-standard-example-annotated.xml` are currently invalid against the 2.01 schema.

https://travis-ci.org/IATI/IATI-Extra-Documentation/builds/31024495

**Comment by caprenter** [comment]
..and I only fixed activity-standard-example-annotated.xml so that it would validate against the schema, it is not necessarily complete as an example.

**Comment by stevieflow** [comment]
I think  `activity-standard-example-annotated-multi.xml` can now be removed - but will check.  

Ill check the org one too

**Comment by stevieflow** [comment]
Have also removed the multi.xml: https://github.com/IATI/IATI-Extra-Documentation/commit/55b3a853d7ff080cfcc6c5d0ffd92d29fdf88073
