### ISSUE TITLE
Organisation standard / budget-line - question

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#194]
http://dev.iatistandard.org/201/organisation-standard/iati-organisations/iati-organisation/total-budget/budget-line/

Should budget-line value(s) sum the parent total-budget / recipient-country-budget / recipient-org-budget value?

**Comment by stevieflow** [comment]
@bill-anderson please can you clarify

**Comment by bill-anderson** [comment]
No. There are too many variables and use cases to try and police this. Leave this for orgs to use as they see fit.

**Comment by stevieflow** [comment]
ok thanks - will close this and have created https://github.com/IATI/IATI-Schemas/issues/239 for schema description text change
