### ISSUE TITLE
Activity Standard - Other Identifier - owner-name

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#195]
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/other-identifier/

Should owner-name be treated as narrative, rather than am attribute, in line with language changes for 2.01?

This way, other names can be provided....

**Comment by stevieflow** [comment]
@bill-anderson is `narrative` needed here ?

If so, then perhaps this needs adding to http://support.iatistandard.org/entries/52824355-Version-2-01-Iteration-3-9-Organisation-and-Activity-Identifiers ?

**Comment by stevieflow** [comment]
If `owner-name` is  "freetext" (as in not a value from a codelist), then should it be a new child element, along with a `narrative`?

**Comment by bill-anderson** [comment]
Discuss this morning

**Comment by stevieflow** [comment]
@bill-anderson to propose way forward in discussion forum

**Comment by stevieflow** [comment]
Resolved through forum and subsequent changes

Extra-Docs commit: https://github.com/IATI/IATI-Extra-Documentation/commit/5dfbf994774d4698fdd283cb95d307b3f14e2f88
