### ISSUE TITLE
contact-info / website

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#196]
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/contact-info/website/

This might need slight review - in light of discussions around activity-website
- Should this element have the URL as an attribute?
- Should narrative be used ?

**Comment by stevieflow** [comment]
Is this relevant still?

**Comment by caprenter** [comment]
This element is designated as anyURI. I think it does the job. Doesn't need a narrative as we don't need to translate URI's and it doesn't need a description text.
@bill-anderson @Bjwebb agree?

**Comment by Bjwebb** [comment]
I think if we think about this too hard, we start getting into activity-website territory, where we start asking whether we can have websites in different languages, and whether we want to be able specify that. However, I think this is much less important for a contact website than for the activity website, and I'm happy for the element to stay as it is.

**Comment by bill-anderson** [comment]
Agree
