### ISSUE TITLE
Codelist section - duplicate pages listed

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#198]
On the left hand navigation within the Codelist section the Codelist management and API pages seem to be list at both the top and bottom of the list of page:

http://iatistandard.org/codelists/

**Comment by stevieflow** [comment]
@Bjwebb

**Comment by stevieflow** [comment]
bump

**Comment by Bjwebb** [comment]
Yes, this is due to the way the toctree glob works. I don't think this is preventing people actually using the site, so I am prioritising it behind other issues atm.

**Comment by Bjwebb** [comment]
I don't think this is urgent to fix, and I don't think I'll get to it before March, so I'm unassigning myself.

**Comment by caprenter** [comment]
I agree, so pushing this top a future milestone

**Comment by amy-silcock** [comment]
This is still an issue. I've added to our maintenance list: https://trello.com/c/g1JPftIC/44-small-codelist-fix

**Comment by samuele-mattiuzzo** [comment]
While looking into this issue, and considering the way (as previously noted by other contributors) Sphinx's GLOB works, I came to realise those two "rogue" items live in the `codelist` subfolder of the repository while not necessarily belonging there as they do not refer to codelist items but are more guidance pages. One option, that would not affect the way the pages are generated, would be to move them out of the `/codelist` folder and reference them differently (eg: `/codelist-guidance/codelist-api.rst`)

@amy-silcock @PetyaKangalova would you agree with the non-technical assessment part of the above comment?
