### ISSUE TITLE
An IATI Activity (from Google Doc)

### ISSUE THREAD

**Issue by jonihillman** [IATI/IATI-Extra-Documentation#20]
Topic: An IATI Activity
Overview: An activity within the organisation being reported to IATI
Description: What an activity is, as decided by the organisation.  It could be a program, a department, a project etc within the organisation.
What is mandatory?: n/a
Things to consider: What is the clearest, and easiest, way to fit what happens in the organisation into ‘activities’
More info: 
Things people ask us: What is an activity?  Who decides what our activities are?

**Comment by stevieflow** [comment]
This is covered through the overview and getting started
