### ISSUE TITLE
Location - clarifiying use of location-id and administrative

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#205]
From guidance note: https://docs.google.com/document/d/1I2zoe-_s75kwDKSkU8BRhAZiTy-Fn2FTiaW4BQFUzus/edit#

`location-id`:

> For administrative areas this identifier should only be used if the location being defined is the administrative area itself. For describing the administrative area/s within which a location falls the location/administrative element should be used.

From @rolfkleef:

> maybe adapt <administrative> with similar text?

Note from @owenscott:

> One slight complication is that both Geonames and OSM contain administrative areas as well as point locations.

Suggestion from @owenscott:

> I'm not sure the best wording, but the idea is as follows:
> 
> location-id: The actual location being described.
> administrative: The higher level administrative polygons within which the location being described is contained.

---

Schema description changes may therefore be needed @Bjwebb @bill-anderson

**Comment by stevieflow** [comment]
@bill-anderson any thoughts on this ?

**Comment by bill-anderson** [comment]
location-id: 
A unique code describing the location according to a recognised gazetteer or administrative boundary repository. Administrative areas should only be reported here if the location being defined is the administrative area itself. For describing the administrative area/s within which a more specific location falls the location/administrative element should be used.

**Comment by stevieflow** [comment]
Thanks - will close this and have created: https://github.com/IATI/IATI-Schemas/issues/240
