### ISSUE TITLE
Location - clarify that multiple administrative elements can be used 

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#206]
... from different vocabs, etc.

As per example provided by @owenscott

`<!-GADM Administrative Areas->
<administrative vocabulary="GADM" level="1" code="8">Shinyanga</administrative>
<administrative vocabulary="GADM" level="2" code="36">Kigoma Urban</administrative>
<administrative vocabulary="GADM" level="3" code="771">Kigoma Bangwe</administrative>
<!-GAUL Administrative Areas->
<administrative vocabulary="GAUL" level="1" code="48362">Kigoma</administrative>
<administrative vocabulary="GAUL" level="2" code="48412">Kigoma Urban</administrative>
<administrative vocabulary="GAUL" level="3" code="49196">Gungu</administrative>
<!-OSM Administrative Areas->
<administrative vocabulary="OSM" level="5" code="1600842">Kigoma</administrative>`

**Comment by stevieflow** [comment]
The example-code could be updated

But - @bill-anderson  does the schema description need changing too?:

> Coded identification of national and sub-national divisions according to recognised administrative boundary repositories. Multiple levels may be reported.

**Comment by bill-anderson** [comment]
Yes. Occurs should be 0..*

**Comment by stevieflow** [comment]
https://github.com/IATI/IATI-Schemas/issues/146 for schema change

Pushing Example XML update to future milestone

**Comment by stevieflow** [comment]
Closing this
