### ISSUE TITLE
Organisation Identifier (from Google Doc)

### ISSUE THREAD

**Issue by jonihillman** [IATI/IATI-Extra-Documentation#21]
Topic: Organisation identifier
Overview: A unique identifier relating to organisation.  This allows users of data to find any individual organisation from all those publishing.
Description: This is a unique identifier of the organisation publishing the information.  This is usually the existing registration number of the organisation with a national governing body.
What is mandatory?  An Organisation Identifier is mandatory for all organisations
Things to consider
More info - for further detail see http://iatistandard.org/organisation-standard/organisation-identifier/
and IATI rules on Org Ids http://iatistandard.org/guides/organisation-data/organisation-identifiers/ {currently draft guidance}
Things people ask us - How do i work out what my Organisation Identifier is?

**Comment by stevieflow** [comment]
Added to Overview text
