### ISSUE TITLE
Schema zip file & README.text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#210]
As per: https://github.com/IATI/IATI-Extra-Documentation/issues/162#issuecomment-51327835
- [x] evaluate whether to add the zip file to /schema
- [x] evaluate / update the README file

**Comment by stevieflow** [comment]
@Bjwebb should we bundle the schema files into a zipped file?

**Comment by Bjwebb** [comment]
Zips are available through GitHub for tagged releases: https://github.com/IATI/IATI-Schemas/archive/v1.05.zip and for branches: https://github.com/IATI/IATI-Schemas/archive/version-2.01.zip

Do we need more than this?

**Comment by caprenter** [comment]
I think @Bjwebb 's point is sufficient
