### ISSUE TITLE
1.05 code-example & changelog updates

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#212]
Update change log on relevant pages in Extra-Docs, if applicable

Pages will be listed here, when finalised

**Comment by stevieflow** [comment]
Only element page to add a changelog statement would be `planned-disbursement`.

As this is just for the description text, Im unsure if this is worth adding currently, given that previous changelog statements on these pages have been centred on whether the element existing or not.

@caprenter @Bjwebb let me know

**Comment by caprenter** [comment]
Key to this change is that previously a description did not exist, and now it does.

I think that's worth noting on the element page.

**Comment by stevieflow** [comment]
OK - will do so , but also minded we discussed with @Bjwebb about how changelog statements could be added to relevant element (as well as codelist) pages - in a future iteration
