### ISSUE TITLE
Activity Status - Suspended

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Extra-Documentation#215]
On the support forum http://support.iatistandard.org/entries/43247528 we have an issue about this that says There is .. a need for new clear user guidance on:
- how to determine what is a current activity
- the omission of forward-looking budgets for suspended activities

and @bill-anderson has stated what that should be.

We need to work out where this goes in the guidance/extra documentation.

The codelist change is here: https://github.com/IATI/IATI-Codelists/issues/47

**Comment by bill-anderson** [comment]
Guidance should explain that the default behaviour of changing the status of an activity (without making any other change relating to this 'suspension') will be:
- Current Activities 
  - Users searching for current activities using activity-status=2 (Implementation) will NOT find this activity. 
- Forward Looking Budgets
  - Users analysing forward looking budgets will continue to see budgets for this activity included.

**Comment by caprenter** [comment]
@bill-anderson has completed this task for 1.05 in this commit:
https://github.com/IATI/IATI-Extra-Documentation/commit/0fe639d55b2611a2060a176c6b2bd4f54db8dd48

but we need to ensure this makes it into 2.01 as well

**Comment by Bjwebb** [comment]
Everything in 1.05 should be merged into 2.01.

**Comment by stevieflow** [comment]
ok - with it being in the 2.01 dev / Overview section that is fine for the purposes of this particular Issue
