### ISSUE TITLE
Update codelist API documentation for 1.05 (and subsequent versions)

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Extra-Documentation#216]
This page needs updating for both 1.05 and 2.01
https://github.com/IATI/IATI-Extra-Documentation/blob/version-1.04/en/codelists/codelist-api.rst

**Comment by stevieflow** [comment]
Im not exactly sure what is needed here

Are we to edit this to say that _from_ 1.04 (and therefore subsequent versions) the codelist API has changed, rather than write new/separate sections for 1.05/2.01 etc...?

**Comment by Bjwebb** [comment]
@stevieflow I think you're right, and it seems @caprenter has already made a stab at this https://github.com/IATI/IATI-Extra-Documentation/pull/219/files

**Comment by caprenter** [comment]
Yes - done.
