### ISSUE TITLE
IATI Identifier (Google Doc)

### ISSUE THREAD

**Issue by jonihillman** [IATI/IATI-Extra-Documentation#22]
https://github.com/IATI/IATI-Extra-Documentation/blob/master/en/iati-activities/iati-activity/iati-identifier.rst

Topic: Activity Identifier
Overview: A unique identifier relating to that activity.  This allows users of data to find any individual activity from all the data published to IATI.
Description: This consists of the IATI Organisation Identifier plus an internal reference unique to the activity, joined together.
What is mandatory?  Having a unique activity identifier for each activity.
Things to consider.  Spaces are not permitted with these - hyphens could be used instead.
More info - for further detail see http://iatistandard.org/activities-standard/iati-identifier/
Things people ask us -
Don't use forward slashes

**Comment by stevieflow** [comment]
Used in overview section
