### ISSUE TITLE
Default language not declared?

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#223]
Looking at the example XML https://github.com/IATI/IATI-Extra-Documentation/blob/version-1.04/en/activity-standard/activity-standard-example-annotated.xml where is `xml:lang="en"`?

I know that we can omit this if we have a default language declared, but that doesn't seem to be done either.

This is a problem in 1.04, 1.05 and 2.01.

**Comment by stevieflow** [comment]
good spot.  I can fix that across all three branches?

**Comment by Bjwebb** [comment]
Fix it on the 1.04 branch, and I'll handle applying the fix to the other branches.

**Comment by stevieflow** [comment]
ok - added

**Comment by Bjwebb** [comment]
@stevieflow Does the multi file also need updating? https://github.com/IATI/IATI-Extra-Documentation/blob/version-1.04/en/activity-standard/activity-standard-example-annotated-multi.xml

**Comment by stevieflow** [comment]
Yes - I did this in https://github.com/IATI/IATI-Extra-Documentation/commit/3420357320914f8f968cba82d622f483c4ed487e

**Comment by stevieflow** [comment]
Ive assigned to you to update for 1.05 and 2.01, but I can also do that ...
