### ISSUE TITLE
Participating Organisation (from Google Doc)

### ISSUE THREAD

**Issue by jonihillman** [IATI/IATI-Extra-Documentation#23]
https://github.com/IATI/IATI-Extra-Documentation/blob/master/en/iati-activities/iati-activity/participating-org.rst

Topic: Participating organisation
Overview: Which organisation is doing what
Description: Used to describe roles organisations play in the activity, whether funding, extending or implementing
What is mandatory?:  Unique IATI identifier for organisations
Things to consider: What role is the organisation playing?
More info
Things people ask us -

**Comment by stevieflow** [comment]
Used in overview section
