### ISSUE TITLE
2.01 - better country/region - better narrative examples

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#232]
These examples are not in line with the rationale for keeping narrative in country/region:

single:

`<recipient-country code="CI">
            <narrative>Ivory Coast<narrative>
    </recipient-country>`

multi-lingual:

`<recipient-country code="CI">
            <narrative>Ivory Coast<narrative>
            <narrative>Côte-d'Ivoire<narrative>
    </recipient-country>`

This isnt the point of keeping `narrative` - any suggestions @bill-anderson

**Comment by bill-anderson** [comment]
Kosovo (UN text)

**Comment by stevieflow** [comment]
We can ask @akerman

**Comment by bill-anderson** [comment]
XK
Kosovo (As per UNSCR 1244)

**Comment by stevieflow** [comment]
@bill-anderson 
How about for `Region`?

**Comment by bill-anderson** [comment]
No current examples. This was included because regions are geopolitical constructs and therefore political variations are theoretically possible

**Comment by Akerman** [comment]
So if I'm understanding this right: you are removing the xml:lang attribute so now you are stuck with issues where text needs to accommodate multiple languages?

**Comment by Akerman** [comment]
Also, as it pertains to the uses of region: How can we allow the standard to accommodate epidemiological boundaries as opposed to or in addition to geopolitical? WHO manages regional projects in this way and I'm sure others dealing with health and humanitarian crisis do too.

**Comment by stevieflow** [comment]
@Akerman thanks for the comments

My mistake on the omission of `xml:lang` in the above example.  I've currently got it as:

`<recipient-country code="CI">
        <narrative>Ivory Coast<narrative>
        <narrative xml:lang="fr">Côte-d'Ivoire<narrative>      
    </recipient-country>`

The issue was to provide a more meaningful example in terms of a) freetext string and b) multi-lingual text

Hence, this is why I thought of your use case.  If you can post the text for that you would (potentially) deploy in this situation, Ill update the example code for the 2.01 documentation

**Comment by stevieflow** [comment]
OK - I've updated this now:
- In the Org standard, Ive updated the example XML to highlight that narrative for `recipient-country-budget/recipient-country/narrative` and `document-link/recipient-country/narrative` should be used for clarification, rather than a simple "name": https://github.com/IATI/IATI-Extra-Documentation/commit/2025924c6e1b02797a44dd3931ebab4cbf85ad4a
- In the activity standard, I've updated `recipient-country` examples in `iati-activity` and `transaction` to include the Kosovo example: https://github.com/IATI/IATI-Extra-Documentation/commit/4e49a6efe50f2627972b37cb7a1e0c6046260122

`<recipient-country code="XK">
        <narrative>Kosovo (As per UNSCR 1244)<narrative>
    </recipient-country>`
- Have added the standard text:

> Note: the `narrative` element is optional and should only be used to provide any essential clarification additional to name available in the `Country` codelist.  
- I've not provided any examples for activity standard `recipient-region/narrative`
- Ive not provided any examples for multi-language of any of these elements

I think that should suffice in terms of examples - please comment/reopen if you see otherwise.

**Comment by caprenter** [comment]
I think the reason we allow narrative on these elements is a little more specific.

It is not simply for clarification.

In fact, really we don't want people to use narrative at all - this is a code field. Supply the code, and then we all know what is being talked about. (this is how all other code fields are now treated)

This is specifically for the case when a publisher has a specific reason to say that the ISO code, and associated look up information does not meet their needs - (for certain publishers, providing information about 'Kosovo' is a case in point)

In our guidence doc about migrating to 2.01 I have written

"Both the recipient-region and recipient-country elements still allow both a code and descriptive text to be specified. This is to cover the cases where the organisation publishing the data may not agree with name of a country or region given by the lookup codelists IATI uses."

I think the update you have done could better reflect this.

**Comment by bill-anderson** [comment]
Agree.

Could even say "isolated cases"

**Comment by stevieflow** [comment]
OK- thanks

Have added the standard text in all instances where we have a narrative for country/region (including in transaction and recipient-country-budget and org/document-link)

> Note: Both the `recipient-region` and `recipient-country` elements still allow both a `@code` and descriptive text to be specified. This is to cover the isolated cases where the organisation publishing the data may not agree with name of a country or region given by the lookup codelists IATI uses.

I've also removed the narrative line from the organisation standard example XML.  The knock on is this Issue: https://github.com/IATI/IATI-Extra-Documentation/issues/261
