### ISSUE TITLE
Changelog notice on each element / codelist page

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#237]
Devise effective ways to use changelog on individual element/codelist pages.

Especially for:
- new elements for 2.01 - eg: `budget-line`
- existing elements that have been adapted: eg; the multiple `narrative` elements

@caprenter suggests we could situate some of this under a "How does this differ from versions 1.x?" banner...

**Comment by caprenter** [comment]
..because in effect 2.01 is a new version. Although it is built of 1.x, there are no changes in version 2 yet - there will be when we have version 2.02 say), so the changelog is empty, but it would be useful to say how it differs from version 1.x

**Comment by Bjwebb** [comment]
@caprenter Surely changes in 2.01 over 1.0x belong in the changelog?

**Comment by caprenter** [comment]
They surely do

**Comment by stevieflow** [comment]
have renamed this as a task to add the changelog for each element page

**Comment by stevieflow** [comment]
Closing - as the actual task is in https://github.com/IATI/IATI-Extra-Documentation/issues/240
