### ISSUE TITLE
transaction / provider/receiver org - example-code text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#238]
In 1.04 we have this example

`provider-org`:

> The full name of the organisation making the financial transaction (receiving in the case of loan and interest repayments).:
- `reciver-org`:

> The full name of the organisation receiving the financial transaction (providing in the case of loan and interest repayments).:

Need to check these exceptions for loan and interest repayments - and find a better way to express this

**Comment by bill-anderson** [comment]
We don't need "The full name of the organisation ..." do we? Is "The organisation ..." sufficient

**Comment by stevieflow** [comment]
Ignore that - it is not applicable in 2.01 (as that is in `narrative`)

The main point of the issue was about the phrasing for how transactions of type loan/loan-repayments needs work

**Comment by stevieflow** [comment]
Im closing this, as it is more about guidance that needs writing, at some point: https://github.com/IATI/IATI-Guidance/issues/143
