### ISSUE TITLE
Schema page needs update

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Extra-Documentation#239]
This page:
http://dev.iatistandard.org/201/schema/

needs an update about the 'other versions of the schema'
alerting @Bjwebb, but you may want to assign to @stevieflow 

Probably needs similar for 1.05?

**Comment by Bjwebb** [comment]
Is it just the "Previous schemas" section that needs updating?

**Comment by caprenter** [comment]
Yes, I think that was all. Checking this page now, all seems fine, apart from spacing between header elements (similar to https://github.com/IATI/IATI-Websites/issues/127 ?)
