### ISSUE TITLE
Reporting Organisation (from Google Doc)

### ISSUE THREAD

**Issue by jonihillman** [IATI/IATI-Extra-Documentation#24]
https://github.com/IATI/IATI-Extra-Documentation/blob/master/en/iati-activities/iati-activity/reporting-org.rst

Topic: Reporting-Org
Overview:  Organisation reporting the activity
Description: The identity of the organisation doing the reporting
What is mandatory?: Unique IATI organisation Identifier
Things to consider: Is the organisation a primary  or secondary reporter
More info
Things people ask us -

**Comment by stevieflow** [comment]
Used in overview section
