### ISSUE TITLE
Country and Region (from Google Doc)

### ISSUE THREAD

**Issue by jonihillman** [IATI/IATI-Extra-Documentation#25]
https://github.com/IATI/IATI-Extra-Documentation/blob/master/en/iati-activities/iati-activity/recipient-country.rst
https://github.com/IATI/IATI-Extra-Documentation/blob/master/en/iati-activities/iati-activity/recipient-region.rst

Topic:Country and region
Overview: Where the funds are going
Description: This is a mapping of where the funds are intended to be used.
This field is mandatory, however, you should report either a country or region.
What is mandatory?: Country or region codes
Things to consider: 
More info:
Things people ask us -

**Comment by stevieflow** [comment]
Used in overview section
