### ISSUE TITLE
Add a list of rules that can't be enforced with the current rulesets framework

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#250]
These are:

`reporting-org/@ref`
- The agency prefix MUST be a valid code in the IATI code list
- The identifier MUST be the same as that recorded by the publisher on the IATI Registry

`iati-identifier`
- ~~MUST be globally unique among all activities published by a single reporting organisation~~ It MUST be globally unique among all activities published through the IATI Registry
- Once an activity has been reported to IATI its identifier MUST NOT be changed in subsequent updates
- It MUST be prefixed with EITHER the organisation-identifier found in `reporting-org/@ref` OR a previous reporting-org identifier reported in other-identifier

`budget`
- The budget element should be repeated for each year of the activity's duration
- Each budget should cover a period no longer than 1 year

I will look into how these can be integrated into the list at http://dev.iatistandard.org/201/rulesets/standard-ruleset/

**Comment by bill-anderson** [comment]
Is that all??

**Comment by Bjwebb** [comment]
Those are the only ones I have identified in https://github.com/IATI/IATI-Schemas/issues/66#issuecomment-54490516 and https://github.com/IATI/IATI-Schemas/issues/67#issuecomment-54490502
- [x] I do also need to add an appropriate [rule for elements at transaction level](https://github.com/IATI/IATI-Schemas/issues/70#issuecomment-50738319)  and for any new changes in [Part 9 of the Iteration 3 proposal](https://github.com/IATI/IATI-Schemas/issues/231).

Please do let me know if I've missed anything else here (that isn't instead enforced in the schema, or listed on http://dev.iatistandard.org/201/rulesets/standard-ruleset/ )

**Comment by Bjwebb** [comment]
I have started adding these rules to http://dev.iatistandard.org/201/rulesets/standard-ruleset/#non-machine-readable-rules

**Comment by Bjwebb** [comment]
I've updated the list at http://dev.iatistandard.org/201/rulesets/standard-ruleset/

Outstanding tasks:
- [ ] Check the list of rules is correct and complete
- [ ] Update the wording of the manual rules for helpfulness and consistency

**Comment by Bjwebb** [comment]
@caprenter Could you take a look at reviewing the rules?

**Comment by caprenter** [comment]
I'm happy that this meets the requirements of our 2.01 Final milestone, but think there is still work to be done here, so putting it to a future milestone and keeping open

**Comment by caprenter** [comment]
@Bjwebb - I've had a go at reviewing the rules page. See what you think.

**Comment by Bjwebb** [comment]
> Some rules are constructed in such a way that a computer could both read the rule, and then check that the rule applies, although software may need to be written to perform achieve this. For example a computer can check that dates have been supplied, and that one is earlier in time than the other. A computer cannot really usefully check that 'a title is meaningful'. 
> 
> Therefore we can split the Standard Ruleset into Machine Readable and Non-Machine Readable Rules

I think this misses the point slightly. The Non-Machine Readable rules could be tested by a computer, it's just we don't have them in a generic format that a generic ruleset parser can interpret. There should be no rules on that page which can not be tested (at least with bespoke code) by a computer. Your 'a title is meaningful' example is not on that page for this reason.

One for us to discuss tomorrow I think.

**Comment by caprenter** [comment]
@Bjwebb Would you have a go at re-writing it then pls?
