### ISSUE TITLE
Changelog on document-link/language

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#255]
@caprenter please can you just double check the changelog statement for this element in 1.04:

http://iatistandard.org/activity-standard/iati-activities/iati-activity/document-link/language/

> Addition of a language element as a child of the document-link element: document-link/language/text() (0..1) - The ISO 639 code for the language of the document

Would I therefore be right in adding a 2.01 changelog to say text() has been removed - but there is no `narrative` element for this?

**Comment by caprenter** [comment]
Yes in 2.01, you now can only supply a code, and no descriptive text - the code is authoritative.
But in 2.01 you can now supply as many language elements as you like, which I believe you can not do in 1.04

**Comment by stevieflow** [comment]
ok - thanks.  Updated changelog text with

> In 2.01 this element usage rules were changed, to allow it to be repeated.
