### ISSUE TITLE
Changelog statements - xsd:date / dateTime

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#256]
@caprenter in elements such as 

http://dev.iatistandard.org/201/organisation-standard/iati-organisations/iati-organisation/recipient-country-budget/period-end/

Would it be advisable to include a changelog statement for 2.01 that mentions xsd:date - in terms of how guidance has been changed?

**Comment by caprenter** [comment]
I don't think it's actually all that important. If you were doing it right before, you will still be doing it right.

If you are new to it, xsd:date tells you all you need to know. Re-open if you think differently.

**Comment by stevieflow** [comment]
Thanks

Shoudl / would the same apply for anyURI too?

**Comment by caprenter** [comment]
Yes I think so.
