### ISSUE TITLE
Changelog - links to old website and wiki

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#257]
@caprenter 

Take a look at http://dev.iatistandard.org/201/activity-standard/iati-activities/

> 1.01
> 
> See previous version on the IATI Standard wiki and website

This isnt in any org pages, and probably not in all activity pages.  Best to remove it in 2.01?

**Comment by caprenter** [comment]
I think the first change was in 1.02 - so yes remove that

**Comment by stevieflow** [comment]
ok - will do so as I go along
