### ISSUE TITLE
Modify guidance on participating-org/@role

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Extra-Documentation#258]
Modify guidance on participating-org/@role : Definition of funding organisation http://support.iatistandard.org/entries/41583626-Modify-guidance-on-participating-org-role-Definition-of-funding-organisation
@stevieflow - can you find out where this should go

**Comment by stevieflow** [comment]
moved to https://github.com/IATI/IATI-Guidance/issues/192
