### ISSUE TITLE
Re-add "Contents of the Ruleset" section

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#265]
This was removed because it was out of date: https://github.com/IATI/IATI-Extra-Documentation/commit/534477eab42a42828516ab6b830e208c7956cea1

**Comment by caprenter** [comment]
Not sure if this is a job for you @Bjwebb so please re-assign if not

**Comment by amy-silcock** [comment]
This is now out of date, no action needed.
