### ISSUE TITLE
Update codelist API page

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#266]
http://dev.iatistandard.org/201/codelists/codelist-api/

This should reflect the CLv3 changes https://github.com/IATI/IATI-Codelists/issues/49, and might make use of the text in https://iati.titanpad.com/154

**Comment by bill-anderson** [comment]
Good

One minor point :"clv1" and "clv2" are used before they are explained

http://iatistandard.org/codelists/downloads/clv2/

**Comment by stevieflow** [comment]
@caprenter what is needed todo on this?

**Comment by akmiller01** [comment]
Reasonably covered by this guidance: https://iatistandard.org/en/guidance/developer/codelist-api/
