### ISSUE TITLE
Include guidance on using XI-IATI

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#267]
(from https://github.com/IATI/IATI-Schemas/issues/237#issuecomment-57171660) 

In the identifiers page on using XI-IATI

**Comment by Bjwebb** [comment]
(Specifically using XI-IATI to refer to a publisher who is not publishing to 2.01 yet, and whose organisation identifier in 1.0x is not valid in 2.01)

**Comment by stevieflow** [comment]
moved to https://github.com/IATI/IATI-Guidance/issues/190
