### ISSUE TITLE
Activity Dates (from Google Doc)

### ISSUE THREAD

**Issue by jonihillman** [IATI/IATI-Extra-Documentation#27]
https://github.com/IATI/IATI-Extra-Documentation/blob/master/en/iati-activities/iati-activity/activity-date.rst

Topic: Activity Dates
Overview
Activity dates provide clear parameters for an activity, signally when an activity starts (or is planned to start) and when it ends (or is planned to end).
Description
There are four different types of activity date:
Start actual - the forecast start date for the activity (e.g. if your activity is in the pipeline stage or you do not know the date of the first disbursement).
Start planned - the actual start date for the activity (e.g. the date of the first disbursement).
End planned - the forecast end date for the activity.
End actual - the actual end date for the activity (e.g. the date of the final disbursement).
What is mandatory?
A start date (planned or actual)
An end date (planned or actual)
Things to consider
Date format must be YYYY-MM-DD (2013-05-22)
A start and end date must be provided - if exact dates are not known then start planned or end planned should be used
Ensure your end date is not before your start date
Dates can be revised at any point
More info
Things people ask us -

**Comment by stevieflow** [comment]
Used in overview section
