### ISSUE TITLE
Review org  ID guidance for 2.01

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#278]
Review http://dev.iatistandard.org/201/organisation-identifiers/

Decide / suggest what needs changing , etc

**Comment by caprenter** [comment]
this work should take account of what has been said here:
http://dev.iatistandard.org/201/upgrades/integer-upgrade-to-2-01/migrating/#organisation-and-activity-identifiers

**Comment by stevieflow** [comment]
Moved into https://github.com/IATI/IATI-Guidance/issues/189
