### ISSUE TITLE
Sector (from Google Doc)

### ISSUE THREAD

**Issue by jonihillman** [IATI/IATI-Extra-Documentation#28]
https://github.com/IATI/IATI-Extra-Documentation/blob/master/en/iati-activities/iati-activity/sector.rst

Topic: Sector
Overview: Providing information on which sector(s) your activity covers helps people compare and aggregate data on different organisations working in the same sector.
Description: There are three different kinds of sector vocabulary in common use:
The OECD Development Assistance Committee’s Creditor Reporting System Purpose Codes (CRS)
The UN Classifications of the Functions of Government (COFOG)
The US National Taxonomy of Exempt Entities (NTEE)
The CRS is the most commonly used
What is mandatory?
Things to consider
More info
Things people ask us

**Comment by stevieflow** [comment]
Used in overview section
