### ISSUE TITLE
Feedback on Country / Region description text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#283]
This might get resolved via Extra-Docs, but putting it here to begin with:

> In reading the Definition for recipient-region, I have to say it’s very confusing. It is not at all clear that region must appear. We either have a region and country or country in our activities. From your definition:
> 
> Recipient-region must not be used merely to describe the region of a country reported in recipient-region, but ONLY if the region is a recipient IN ADDITION to the country.
> 
> Actually, the first part of this sentence may be a typo. Should it read “…describe the region of a country reported in recipient-country”? Isn’t this implying that the region should only appear if it is different than the region of the country. Although, that may be referring to regions inside the country rather than the region containing the country.

**Comment by amy-silcock** [comment]
No further conversation since 2014. Current description can be found here:http://reference.iatistandard.org/203/activity-standard/summary-table/

**Comment by andylolz** [comment]
Looks like the typo described in this feedback was fixed in IATI/IATI-Schemas#259, so that’s good.
