### ISSUE TITLE
IATI Example XML file has country/region percentages that sum to 100

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#287]
https://github.com/IATI/IATI-Extra-Documentation/blob/5dfbf994774d4698fdd283cb95d307b3f14e2f88/en/activity-standard/activity-standard-example-annotated.xml#L92

As http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/recipient-country/ says 

> When both the recipient-region and recipient-country, then the @percentage values should sum to 100% for the specific iati-activity.

**Comment by stevieflow** [comment]
Thanks

**Comment by stevieflow** [comment]
Also edited the code examples -
