### ISSUE TITLE
IATI Example XML does not match final numeric codelists

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#288]
https://github.com/IATI/IATI-Extra-Documentation/blob/5dfbf994774d4698fdd283cb95d307b3f14e2f88/en/activity-standard/activity-standard-example-annotated.xml#L61

`type="1"` is Planned start according to http://dev.iatistandard.org/201/codelists/ActivityDateType/

Other codes/codelists may also want checking

**Comment by stevieflow** [comment]
Thanks - have fixed
