### ISSUE TITLE
Location (from Google Doc)

### ISSUE THREAD

**Issue by jonihillman** [IATI/IATI-Extra-Documentation#29]
https://github.com/IATI/IATI-Extra-Documentation/blob/master/en/iati-activities/iati-activity/location.rst

Topic: Location
Overview: Geographical location relating to the activity
Description: Where the activity takes place.  This can be split across multiple locations using percentages, and can include coordinates to show precise location.
What is mandatory?: A country code in 2 digit format
Things to consider: Including coordinates.
More info: for more detail see http://iatistandard.org/activities-standard/location/
Things people ask us:

**Comment by stevieflow** [comment]
Added to overview section
