### ISSUE TITLE
activity-date rules - wrong code values 

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#291]
From @pell
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/activity-date/

http://dev.iatistandard.org/201/codelists/ActivityDateType/

The rules seem to reference the wrong codes, specifically:

```
activity-date[@type='1'] must be before activity-date[@type='2']
activity-date[@type='3'] must be before activity-date[@type='4']
```

Should be

```
activity-date[@type='1'] must be before activity-date[@type='3']
activity-date[@type='2'] must be before activity-date[@type='4']
```

Also "be before" might be best as "before or equal to" ?

**Comment by pelleaardema** [comment]
In addition:
`activity-date[@type='1' or @type='3'] must be present`.
Doesn't make sense. Why would you require a planned start or end date?
Probably should be: `activity-date[@type='1' or @type='2'] must be present`. (requiring a start date)

`activity-date[@type='3'] must be today, or in the past`.
and
`activity-date[@type='4'] must be today, or in the past`.
Now require the end dates to be in the past... not sure what was meant here? And given the fact that activity-status 'Pipeline/identification' is also possible: why would you require any date to be in the past?

**Comment by stevieflow** [comment]
Hi @pelleaardema 

Yes, thanks for the additional coments

Requiring a start date (either planned or actual) - codes 1 & 2 - yes, this is in line with the 2.01 requirements ("a start date")

"must be today, or in the past" - also correct, this should apply to `start` type dates (codes 1 & 2)

Apologies for our miscoding here

**Comment by pelleaardema** [comment]
Hi @stevieflow 

Re: "must be today, or in the past" - I don't think you can enforce this. Given the fact that organisations are able to post activities that have a status "Pipeline/identification" they're able to publish activities _that haven't started yet_, so with a start date that lies somewhere in the future.

**Comment by stevieflow** [comment]
"must be today, or in the past"  should be true for start-actual though (but maybe not start-planned) ?

**Comment by pelleaardema** [comment]
So you'd consider a project that is in the pipeline/identification phase (activity-status="1") to be started already?

**Comment by stevieflow** [comment]
In terms of activity-status=pipeline as an exception to the condition of a mandatory `<activity-date>`, there is this discussion between @markbrough & @bill-anderson : 

http://support.iatistandard.org/entries/41089758-Modify-activity-date-validation-and-guidance

Can either of you assist @pelleaardema ?

**Comment by pelleaardema** [comment]
@stevieflow 
This doesn't really cover the concern. I can imagine you'd want to make a start-planned date mandatory. 
But the rules currently say it _should be in the PAST_  (and that can't be made mandatory IMO)

**Comment by stevieflow** [comment]
@pelleaardema yes - as mentioned above at https://github.com/IATI/IATI-Extra-Documentation/issues/291#issuecomment-66754090 - _in the past_ might not be a good rule for start-planned

**Comment by Bjwebb** [comment]
Agree that this is a bug, and with the changes you've suggested are what was intended.

The final rule should be that both Actual Start dates, and Actual End dates should be in the past, because if they're not in the past, you don't know they've actually happened yet. So, the rules should be:

```
activity-date[@type='2'] must be today, or in the past.
activity-date[@type='4'] must be today, or in the past.
```

**Comment by caprenter** [comment]
For clarity (discuss!)...

The reason for this is that in the final stages of agreeing this list we changed the codes to group start and end values together.

For reference:
1 = Planned start
2 = Actual start
3 = Planned End
4 = Actual end

Currently 5 of our 6 rules are wrong:

```
activity-date[@type='1' or @type='3'] must be present.

activity-date[@type='1'] must be before activity-date[@type='2']

activity-date[@type='3'] must be before activity-date[@type='4']

activity-date[@type='3'] must be today, or in the past.

activity-date[@type='4'] must be today, or in the past.
```

We will change this to be:

```
activity-date[@type='1' or @type='2'] must be present.

activity-date[@type='1'] must be before activity-date[@type='3']

activity-date[@type='2'] must be before activity-date[@type='4']

activity-date[@type='2'] must be today, or in the past.

activity-date[@type='4'] must be today, or in the past.
```

**Comment by Bjwebb** [comment]
This has been updated now: http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/activity-date/
