### ISSUE TITLE
Document Link States Title OR Category Is Mandatory At V2.01

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Extra-Documentation#295]
http://iatistandard.org/201/activity-standard/overview/linked-documents/ currently states that EITHER title OR category are required for a document link. However, 
http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/document-link/title/ and http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/document-link/category/ suggest that both are required

**Comment by caprenter** [comment]
Thanks @iatisupport you are right. 
In version 2.01:
The schema says you must have a title (and only one), and you must have at least one category.
See: https://github.com/IATI/IATI-Schemas/blob/version-2.01/iati-activities-schema.xsd#L2350

However this is not the same for version 1.x, so the documentation needs to make sure it is version specific.

We need to edit this document: https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.01/en/activity-standard/overview/linked-documents.rst

**Comment by stevieflow** [comment]
OK thanks @iatisupport @caprenter 

I'm just checking the following two lines:

> For every document presented either a title or category is expected (or both).

I can split this into two lines:

> For every document presented both a title and a category is expected
> Multiple categories can be expressed for any document, by repeating the `category` element.

 I think the latter also applies to 1.0x?

**Comment by caprenter** [comment]
On re-reading, I think the key word here is 'expected'. I'm not sure why the word 'required' is not being used. I think they mean slightly different things, and the OP read expected as requires IMHO.

So 

> For every document presented a title and at least one category is required

is accurate for 2.01

To be broader perhaps:

> For every document presented both a title and category is expected. In fact in version 2.01 a title and at least one category are required. This rule is enforced by the schema.

The multiple categories line is also helpful.
