### ISSUE TITLE
Describing documents in different languages

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#296]
@iatisupport @caprenter 

Observed via looking at #295 :

> The same document can be presented in different languages via separate document-link elements.

Does this still stand for 2.01?  My understanding is that it does.  This means that the _target_ document can be in multiple languages.  As `document-link` can only contain one URI, so should the documentation be:

> If the documents are in different languages, which are available at different URLs, then repeat the `document-link` element

and

> If the target document has multiple languages within it, then repeat the `language` element

**Comment by caprenter** [comment]
Yes, I believe this is still the same in 2.01, and think your suggested documentation is good.

The existing documentation is not wrong, but your clarification helps.

**Comment by stevieflow** [comment]
@caprenter should I update the documentation for 1.0x and 2.01 to include this extra clarification?

**Comment by caprenter** [comment]
I'm not too bothered. Changes to below 1.05 are unlikely to applied in the near future. I think the current documentation is sufficient, but that your suggestion helps. Apply it if you have time

**Comment by stevieflow** [comment]
ok - have just applied to 2.01

**Comment by amy-silcock** [comment]
http://reference.iatistandard.org/203/activity-standard/overview/linked-documents/
