### ISSUE TITLE
Budget (from Google Doc)

### ISSUE THREAD

**Issue by jonihillman** [IATI/IATI-Extra-Documentation#30]
https://github.com/IATI/IATI-Extra-Documentation/blob/master/en/iati-activities/iati-activity/budget.rst

Topic: Budget
Overview: Information on any forward-looking budget relating to the activity
Description: Budget information that can be made available online, and linked to within the IATI data.  Forward-looking information such as budgets are an essential part of making information useful in planning and accountability.
What is mandatory?: Budget information is not mandatory, but will provide vtial forward-looking information to allow resources for poverty reduction to be allocated and spent more effectively.
Things to consider: How easy is your budget information to understand?  
More info: 
Things people ask us:

**Comment by stevieflow** [comment]
Used in overview section
