### ISSUE TITLE
Clarify Usage For Capital Spend Element

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Extra-Documentation#301]
The definition for Capital Spend states that it is 'The percentage of the total commitment that is for capital spending'. However, the example usage 'uses the @percentage attribute to state 88.8% of the iati-activity budget is for capital expenditure.' 

As a result the example usage should be amended to read '88.8% of the iati-activity total commitment is for capital expenditure.' so that it is in line with the element definition

**Comment by amy-silcock** [comment]
This change has been implemented: http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/capital-spend/
