### ISSUE TITLE
Guidance - register datasets on the Registry

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#306]
(I think this is the most appropriate repo for this...)

I noticed that this page: http://iatiregistry.org/help doesn't include any guidance on how to register new datasets, once you have an account & publisher org.  

It might be worth describing this process on this page, and also synching up with: http://iatistandard.org/201/guidance/how-to-publish/publish-files/#add-details-of-your-datafiles ?

**Comment by amy-silcock** [comment]
This is now covered in by the new IATI website: https://iatistandard.org/en/guidance/preparing-organisation/organisation-account/how-to-register-with-iati/
