### ISSUE TITLE
policy-marker : inconsistent example

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Extra-Documentation#307]
Guidance for the [PolicySignificance codelist](http://iatistandard.org/201/codelists/PolicySignificance/) states that:

```
Policy Significance code = 4 (Explicit primary objective) SHOULD ONLY be used in conjunction with Policy Marker code = 9 (Reproductive, Maternal, Newborn and Child Health)
```

However, the [documentation (pre-v2.02)](http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/policy-marker/) uses an example:

```
<policy-marker vocabulary="1" code="1" significance="4" />  
```

This example should be fixed and checks undertaken for similar versions in other versions of the standard.

**Comment by amy-silcock** [comment]
This change has been implemented: http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/policy-marker/#iati-activities-iati-activity-policy-marker-vocabulary
