### ISSUE TITLE
Budget Identfier Sector (category) - spelling mistake

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#308]
http://iatistandard.org/201/codelists/BudgetIdentifierSector-category/

The title for this codelist omits the second in Identifier:

> Budget Identfier Sector (category)

Should be

> Budget Identifier Sector (category)

This misspelling is also listed on http://iatistandard.org/201/codelists/

**Comment by dalepotter** [comment]
Great spot - thanks for highlighting this one, which seems to arise from the [codelist itself](https://github.com/IATI/IATI-Codelists/blob/version-2.01/xml/BudgetIdentifierSector-category.xml#L4).

As this is an Embedded list, I'll clarify the process on fixing typos outside of a formal upgrade process.

**Comment by amy-silcock** [comment]
The Budget Identfier Sector (category) is now a non-embedded codelist, so we can fix the type as a bug fix.

**Comment by amy-silcock** [comment]
This has now been fixed: http://reference.iatistandard.org/203/codelists/
