### ISSUE TITLE
Guidance listed on Codelist list

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#309]
http://iatistandard.org/201/codelists/ 

In the list of codelists, there is an entry for:

> Guidance

This isnt an actual codelist, so should be removed

**Comment by dalepotter** [comment]
Thanks Steven. It seems that the 'Guidance' link is directing to a subheading here in the [Policy significance codelist](http://iatistandard.org/201/codelists/PolicySignificance/#guidance). We'll look into how this page is generated shortly.

Thanks again.

**Comment by amy-silcock** [comment]
This has been removed: http://reference.iatistandard.org/203/codelists/
