### ISSUE TITLE
iati-actvity code example missing description of humanitarian attribute

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#315]
The code example for `iati-activity`: http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/  does not include any descriptive text for the inclusion of the @humanitarian attribute, as per other attributes- eg:

> The optional @hierarchy attribute of is set as 1

**Comment by amy-silcock** [comment]
The page now includes a descriptive text for the humanitarian attribute: http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/
