### ISSUE TITLE
Location sub-elements - code examples not succinct

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#318]
Taking a look at the code example for a page such as 
http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/location/location-reach/

The code example doesn't seem to "stop"

This seems to be because https://raw.githubusercontent.com/IATI/IATI-Extra-Documentation/version-2.02/en/activity-standard/iati-activities/iati-activity/location/location-reach.rst has:

`end-before: <!--location ends-->`

I think it needs to be

`end-before: <!--location-single ends-->`

@dalepotter this was probably my bad originally!  I can try and fix this in the next weeks?

**Comment by amy-silcock** [comment]
This looks to be fixed: http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/location/

Let me know if not.

**Comment by stevieflow** [comment]
Thanks @amy-silcock 

I can see that http://reference.iatistandard.org/202/activity-standard/example-xml/ is now edited
