### ISSUE TITLE
Remove Reference To Policy Vocabulary & Add Link To Guidance For Humanitarian Reporting

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Extra-Documentation#319]
Zendesk ticket 3985 relates.

The Humanitaraian Reporting overview at http://iatistandard.org/202/activity-standard/overview/humanitarian-reporting/ currently contains a reference to "PolicyMarkerVocabulary - code "2" defines the list of UNOCHA humanitarian policies to which a specific activity relates."

However, for various reasons this policy vocabulary does not yet exist so the reference to it should be removed for the moment.

Also, it would be useful to create a link to some additional humanitarian reporting guidelines that are currently out for review and testing by the wider IATI Community at: http://discuss.iatistandard.org/t/help-develop-iati-s-humanitarian-reporting-guidance/530/

**Comment by hayfield** [comment]
Fixed in #320 

There are currently no plans to add this as a Code.
