### ISSUE TITLE
Amend Humanitarian Scope Documentation To Use Glide IDs (not Numbers)

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Extra-Documentation#321]
Currently the standard documentation for humanitarian scope uses examples that contain GLIDE numbers rather than GLIDE Ids

**Comment by amy-silcock** [comment]
This looks like it has been fixed: http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/humanitarian-scope/

Let me know if not.
