### ISSUE TITLE
TransactionType codelist missing changelog update (2.02)

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#325]
This list:

https://github.com/IATI/IATI-Extra-Documentation/blob/87589337ce66298f2d612d5f7722d0bd365b7efe/en/codelists/TransactionType.rst

is missing the reference to the fact that Incoming Commitment was added in 2.02

Referenced here: http://iatistandard.org/202/upgrades/decimal-upgrade-to-2-02/2-02-changes/

**Comment by dalepotter** [comment]
Thanks for flagging this @stevieflow - this change has now been resolved: http://iatistandard.org/202/upgrades/decimal-upgrade-to-2-02/2-02-changes/
