### ISSUE TITLE
Clarify best practice on transactions / budgets

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#33]
How much aggregation would we like to see on transactions / budgets:

Transactions:

Current year: Monthly
Previous three years: Quarterly
Previous other years: Annual

Budgets
Previous years: annual
Forward looking: quarterly

**Comment by bill-anderson** [comment]
I think documenting best practice like this is over complicated and confusing. Propose we keep this simple.

Best practice (and minimum ask) on aggregation is:
Transactions - monthly (quarterly)
Budgets - annual in line with recipient fiscal year, or quarterly (annual)

Guidance should be that new publishers aim for best practice on current data (NB not current activities) and stick to that moving forward. Earlier data on current activities is a "publish what you can" issue.

I am not persuaded that sticking to this over a period of time runs into big data problems. IATI data is generally not very big.

**Comment by stevieflow** [comment]
Propose to move this from 1.04 as it has to be general guidance

**Comment by bill-anderson** [comment]
Agreed

**Comment by stevieflow** [comment]
Moved to https://github.com/IATI/IATI-Guidance/issues/42
