### ISSUE TITLE
Unclear use of International Dialling Codes

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#330]
https://github.com/IATI/IATI-Extra-Documentation/blob/2a279c7ac0fdd8eda7ac594af2c6ebee2cd59bb5/en/activity-standard/overview/contact-info.rst#user-content-considerations

This states that `For telephone pay attention to international dialling codes`. This is unclear whether international dialling codes should be included or not.

The [telephone](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/contact-info/telephone/) element documentation does not provide clarification.

**Comment by bill-anderson** [comment]
'Pay attention' is a bit dodgy

Guidance should be "telephone numbers should include the international dialing code". We don't need to police this

**Comment by amy-silcock** [comment]
@Petya ready to be reviewed

**Comment by amy-silcock** [comment]
This change has been implemented: http://reference.iatistandard.org/203/activity-standard/overview/contact-info/
