### ISSUE TITLE
Mis-spelled receiver-org

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#333]
The [Org IDs](http://iatistandard.org/202/organisation-identifiers/) page references `reciver-org`. This should be `receiver-org`.

https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.02/en/organisation-identifiers.rst

**Comment by amy-silcock** [comment]
This has been fixed: http://reference.iatistandard.org/203/organisation-identifiers/
