### ISSUE TITLE
Guidelines - Well Formed and Valid

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#335]
As part of the investigation under #334 - identifying _must_ statements among Guidelines.

http://iatistandard.org/202/activity-standard/overview/activity-file/
`It must be well-formed XML.`
`It must validate against the relevant version of the IATI activity schema`

These relate to [potential changes to the Introduction](https://discuss.iatistandard.org/t/notes-from-standards-day/762/5).

**Comment by amy-silcock** [comment]
This is inherent within the IATI Standard and rules of xml. New guidance on activities can be found here: https://iatistandard.org/en/guidance/preparing-data/activity-information/
