### ISSUE TITLE
Guidelines - Making Root Element Mandatory

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#336]
As part of the investigation under #334 - identifying must statements among Guidelines.

http://iatistandard.org/202/activity-standard/overview/activity-file/
`Any activity file must have iati-activities as the root element - to contain all other elements.`

The Schema does not require this (though it could). It should be a _should_.

**Comment by amy-silcock** [comment]
If this is not present the file does not exist.
