### ISSUE TITLE
Guidelines - Inconsistent Intended Reader

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#337]
The Guidelines (Consideration lists) within the [activity](http://iatistandard.org/202/activity-standard/overview/) and [org](http://iatistandard.org/202/organisation-standard/overview/) have an inconsistent intended reader.

For example, on http://iatistandard.org/202/activity-standard/overview/activity-file/
`When creating the activity file it is recommended to avoid spaces and non-ascii characters in file names and urls.`
reads as if a publisher is reading it while
`Ideally, this link would be to an activity file(s) on the publisher website or open data portal`
reads as though it's intended for somebody who wants to find out about IATI, and
`An IATI publisher should publish at least one activity file`
could be intended for either depending on which person it's read in.

It should be made consistent, both on the example page and throughout the rest of the Guidelines.

**Comment by amy-silcock** [comment]
Now included in #522
