### ISSUE TITLE
Guidelines - Large Variety of Levels of Recommendation

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#338]
The Guidelines (Consideration lists) within the [activity](http://iatistandard.org/202/activity-standard/overview/) and [org](http://iatistandard.org/202/organisation-standard/overview/) have a very large range of ways in which to define how recommended something is, but with no consistency.

For example, on http://iatistandard.org/202/activity-standard/overview/iati-activity/
`must`
`must [...] be considered`
`are mandatory`
`Publishers can`
`A publisher can`
`A [element] can`
`It is recommended that`
`should`
`should be considered`
`should [...] where possible`
This many different ways on a single page is too many, and there are even more varieties across a range of pages!

The way in which the levels of recommendation within Guidelines are defined should be made consistent.

**Comment by amy-silcock** [comment]
Now included in #522
