### ISSUE TITLE
Guidelines - Format of IATI Identifier

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#339]
http://iatistandard.org/202/activity-standard/overview/iati-identifier/

This page states that `It is recommended to avoid spaces and non-ascii characters.`

* It does not state where spaces and non-ascii characters are to be avoided
* The previous Consideration states that `It is recommended that no forward slashes (/) or spaces should be contained within the iati-identifier` - this is repeated information
* This indicates that all ascii characters other than a space (character 32) are OK. There are other characters on http://www.asciitable.com/ that should be avoided far more than spaces!

**Comment by amy-silcock** [comment]
Now included in #522
