### ISSUE TITLE
Clarification of budget vs transaction commitments

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#34]
From Bill

That is exactly the correct usage of Commitment

For traditional donors commitments are made at the outset of an activity: "We commit to spend $10m spread over x years." If the total commitment changes during the lifetime of the activity a delta transaction is record (ie. if reduced you would report a negative transaction on the date the decision to reduced is made.) So the sum of commitments on an activity is effectively the total budget, and in the real-world this is typically a one-off decision taken at the beginning.

i.e. in most cases commitment = total budget

The budget element should not be used for a total budget, bit only for forward-looking annual or quarterly breakdowns of the total budget. This data does not have the 'legal' status of a commitment - its more indicative and subject to change. i.e. "We have a fixed budget for this project but we cannot be certain exactly when it is going to be spent."

 NB. Commitments must show delta changes as they are a part of the audit: They reflect particular decisions. Budgets should not be deltas, but must be replaced (not added to) whenever a change is made.

**Comment by stevieflow** [comment]
This was from an old email thread - proposal to push this into post 1.04 guidance tasks

**Comment by bill-anderson** [comment]
I'm happy for some delay to ease the work load. But this was confirmed in Montreal and does not require consultation. Would prefer it to go in now as it is quite important (along with distinction between budget and planned-disbursement)

**Comment by stevieflow** [comment]
putting into post-1.04 just for now

**Comment by stevieflow** [comment]
Closing, as this is now in Guidance repo: https://github.com/IATI/IATI-Guidance/issues/41
