### ISSUE TITLE
Guidelines - Simultaneous use of both original and final values

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#340]
As highlighted in https://discuss.iatistandard.org/t/clarifying-the-relationship-between-original-budget-and-revised-budget-in-iati-activities/819 

At present, it is not clear that it is permitted to have both original and final versions of values that comes in these formats.
Similarly, it is not clear that there may be multiple defined values of each type (should it have been revised multiple times).

This occurs with, `activity-date`s and `budget`s (and potentially others?)

**Comment by hayfield** [comment]
http://iatistandard.org/202/activity-standard/overview/dates/ `Any start date should be before the end date, or the same` implies that end dates are singular, though this is not mentioned anywhere.

**Comment by amy-silcock** [comment]
Consultation on budgets has taken place and the new guidance can be found here: https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.03/en/activity-standard/overview/budgets.rst and https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.03/en/organisation-standard/overview/budgets.rst.

The new guidance pages will replace the previous reference site in the switch to the new website.
