### ISSUE TITLE
Guidelines - Unclear how and where to define Org Names

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#341]
http://iatistandard.org/202/activity-standard/overview/organisations/
`Any freetext name for an organisation, must be included in the child narrative element, which can be repeated for different languages.`

Reference to `the child narrative element` indicates that the child element is singular when there can actually be multiple.
Also, `Any freetext name for an organisation` includes any possible name for an organisation, rather than being limited to the name of the organisation being referenced.

In general, this needs significantly re-wording.

**Comment by amy-silcock** [comment]
Now included in #522
