### ISSUE TITLE
Guidelines - Document Category Prefix

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#343]
http://iatistandard.org/105/activity-standard/overview/linked-documents/
`For document category in the IATI activity standard, it is expected that the DocumentCategory code would be have the A prefix.`

The [relevant Codelist](http://iatistandard.org/202/codelists/DocumentCategory/) is only used in this manner. It contains codes without an `A` prefix. Is the Guideline saying that it is expected that these codes (`B`-prefix) are never used?

**Comment by andylolz** [comment]
The complementary line is here:

http://iatistandard.org/203/organisation-standard/overview/documents/

> For document `category` in the **IATI organisation standard**, it is expected that the _DocumentCategory_ code would be have the _B_ prefix.

Both statements contain lots of typos, and are a bit tricky to decipher. But I think the sentiment (that codes used for activity docs should begin with an `A`, and for org docs should begin with a `B`) is correct.

**Comment by amy-silcock** [comment]
Now included in #522
