### ISSUE TITLE
Guidelines - Unclear example phrasing

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#344]
http://iatistandard.org/105/activity-standard/overview/linked-documents/
`The activity-website should be a URL to a page or website that is specifically about the iati-activity - not generic information (eg: http://www.example.com/en/activity/ABC123).`

The phrasing means that it is unclear whether the example is specific or generic.

**Comment by amy-silcock** [comment]
This is no longer an issue in version 2 documentation: http://reference.iatistandard.org/203/activity-standard/overview/linked-documents/
