### ISSUE TITLE
Guidelines - Use of CAPITALS and jargon

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#345]
There are a number of Guidelines stating that in particular situations, CAPITALS or jargon should not be used.

http://iatistandard.org/105/activity-standard/overview/contact-info/
`The free-text instances of organisation, person-name, job-title and mailing-address should avoid use of text in CAPITALS, where possible.`
http://iatistandard.org/105/activity-standard/overview/conditions/
`The free-text to describe the condition should avoid jargon`

http://iatistandard.org/105/activity-standard/overview/iati-activity/
`It is recommended that the title should be concise and jargon-free`
`The free-text instances of title and description should avoid use of text in CAPITALS, where possible.`

The implication is that it is perfectly fine to use CAPS TEXT and jargon in all instances where it is not explicitly stated that these should be avoided.

The guidance on these things should be generalised rather than focusing on a few specific instances.

**Comment by amy-silcock** [comment]
To be noted for when the overview pages are re-written. As these are not contradictions between the overview page and the schema or ruleset, I will close this issue.

**Comment by andylolz** [comment]
Once overview pages have been rewritten it makes sense to close. At the moment, this issue is still valid – so I don’t understand why it would be closed.

**Comment by amy-silcock** [comment]
Hi @andylolz, my current thought is to condense future improvements into a single issue. Then they're grouped for a time when work on the overview pages is decided.

How does that sound?

**Comment by andylolz** [comment]
> my current thought is to condense future improvements into a single issue

+1, that sounds great. My fear was just that once it’s closed, this (valid) issue is basically lost forever.

If your intention is to merge and replace, then that’s fine / better than fine 👍

**Comment by amy-silcock** [comment]
Now included in #522
