### ISSUE TITLE
Guidelines - Duplication of Ruleset Contents

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#346]
As part of the investigation under #334 - identifying must statements among Guidelines.

There are several Guidelines that are contained within the [Standard Ruleset](http://iatistandard.org/202/rulesets/standard-ruleset/).

http://iatistandard.org/202/activity-standard/overview/iati-activity/
`Every iati-activity must have a globally unique iati-identifier`

http://iatistandard.org/202/activity-standard/overview/iati-identifier/
`The iati-identifier must be unique for every iati-activity within the complete dataset published.`

http://iatistandard.org/202/activity-standard/overview/classifications/
`A sector is mandatory.` - note that the details here are unclear (without investigation, it [looks like](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L136) they are optional in the Schema)

http://iatistandard.org/202/activity-standard/overview/budgets/
`When declaring a value-date for any budget, this date must be in the past.`

http://iatistandard.org/105/activity-standard/overview/transactions/
`Neither of transaction-date and value-date can be in the “future”. `

**Comment by amy-silcock** [comment]
Must statements among guidelines are allowed as long as they match what's in the Standard. Sector is mandatory at activity or transaction level - not both.

The new overview pages better explain the rules and guidance for each element. In the move to the new website these will replace the current overview pages.
