### ISSUE TITLE
Guidelines - Contradictions with Rulesets

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#348]
As part of the investigation under #334 - identifying must statements among Guidelines.

There are several Guidelines that contradict Rules within the [Standard Ruleset](http://iatistandard.org/202/rulesets/standard-ruleset/).

http://iatistandard.org/202/activity-standard/overview/iati-identifier/
`The iati-identifier must begin with an reporting-org identifier that has a value published on the OrganisationRegistrationAgency codelist.` contradicts `It MUST be prefixed with EITHER the organisation identifier found in reporting-org/@ref OR a previous reporting-org identifier reported in other-identifier`

http://iatistandard.org/202/activity-standard/overview/classifications/
`When multiple sector are described, then a @percentage should be declared for each. This should sum to 100% for each iati-activity.`

http://iatistandard.org/202/activity-standard/overview/classifications/
`Multiple or singular policy-marker can also be described. Unlike sector, a percentage is not required.` - a percentage is only required for sectors if there are multiple sectors defined against a single activity.

http://iatistandard.org/202/activity-standard/overview/budgets/
`A budget must not span a period greater than one year.` - the Ruleset states that `Each budget should cover a period no longer than 1 year` (a _should_ in the Ruleset means it is not a Rule!)

**Comment by amy-silcock** [comment]
PRs are:  #517, #518 and #519

**Comment by amy-silcock** [comment]
> http://iatistandard.org/202/activity-standard/overview/classifications/ When multiple sector are described, then a @percentage should be declared for each. This should sum to 100% for each iati-activity.

and

> http://iatistandard.org/202/activity-standard/overview/classifications/
Multiple or singular policy-marker can also be described. Unlike sector, a percentage is not required. - a percentage is only required for sectors if there are multiple sectors defined against a single activity.

Fixed in #517, #518, #519, #520 and #521

**Comment by amy-silcock** [comment]
> http://iatistandard.org/202/activity-standard/overview/budgets/
A budget must not span a period greater than one year. - the Ruleset states that Each budget should cover a period no longer than 1 year (a should in the Ruleset means it is not a Rule!)

This is rule in the definition of the element: http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/budget/period-end/. No change needed.

**Comment by amy-silcock** [comment]
@PetyaKangalova to review

**Comment by amy-silcock** [comment]
These changes have been implemented.
