### ISSUE TITLE
Guidelines - Checked by Schema

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#349]
As part of the investigation under #334 - identifying must statements among Guidelines.

There are several Guidelines that make statements about things that are checked by the Schema.

http://iatistandard.org/202/activity-standard/overview/activity-file/
`The version of the IATI standard being used must be declared via the version attribute of the iati-activities element.`

http://iatistandard.org/202/activity-standard/overview/dates/
`Date format for activity-date, period-start, period-end, transaction-date and value-date must be in ISO 8601 (YYYY-MM-DD), eg: 2014-03-21`
`Date format for generated-datetime last-updated-datetime must use ISO 8601 date format, e.g. “2014-03-21T18:45:00+01:00”.`

http://iatistandard.org/202/activity-standard/overview/geography/
`When describing the recipient-country the relevant Country code must be used.`
`When describing the recipient-region the relevant Region code must be used.`

http://iatistandard.org/202/activity-standard/overview/budgets/
`For planned-disbursement it is valid to only report the period-start as a single date.` ...I think - what does this even mean?

http://iatistandard.org/105/activity-standard/overview/transactions/
`Every transaction must contain a transaction-date , value, value-date and transaction-type.` - also confusing since `value-date` is an attribute, while the others are [subelements](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/transaction/#subelements)
`Both the transaction-date and value-date must be in ISO 8601 format (YYYY-MM-DD), eg: 2014-03-21.`

http://iatistandard.org/105/activity-standard/overview/conditions/
`An iati-activity does not require a conditions statement, if none are relevant.`

**Comment by amy-silcock** [comment]
The examples highlighted here are from the overview pages. None of these examples contradict the schema.

Discussion about how these should be presented can be found here: #334 

As there is no further action from this issue, I will close it.
