### ISSUE TITLE
Spaces in file names

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#35]
Documentation is needed for this

**Comment by Bjwebb** [comment]
Do you mean spaces in the url of the IATI XML file? Spaces should be acceptable (if possibly unwise), provided they're properly encoded.

Adding spaces to urls/file names is one of the things that is permitted, but may be problematic for people trying to use the data, and making naive assumptions. Another similar issue is using non-ascii characters in file names and urls.

**Comment by stevieflow** [comment]
That's the guidance I was talking about!

**Comment by stevieflow** [comment]
Added to org and activity file overview pages: https://github.com/IATI/IATI-Extra-Documentation/commit/5f441deabfed6969681eb3a39e4560856e2e8d90
