### ISSUE TITLE
Guidelines - Contradictions with Schema

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#350]
As part of the investigation under #334 - identifying must statements among Guidelines.

There are several Guidelines that make statements that contradict the Schema.

http://iatistandard.org/202/activity-standard/overview/dates/
`Dates should be a valid xsd:date, and a datetimes should be a valid xsd:dateTime.` (it is defined in the Schema that [they](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L47) [must](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L698))

http://iatistandard.org/202/activity-standard/overview/classifications/
`A @vocabulary can be declared when describing a sector. This should be on the Vocabulary codelist.` - it _must_ be.

http://iatistandard.org/202/activity-standard/overview/classifications/
`Multiple or singular policy-marker can also be described. Unlike sector, a percentage is not required.` - there is nothing in the Schema to allow a percentage to be defined (well, apart from extensions).

http://iatistandard.org/202/activity-standard/overview/budgets/
`It is possible to report budget values in multiple currencies` - a budget value may be [stated only once](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L2255), and currency is a singular attribute on here, so you cannot state the value in multiple currencies

http://iatistandard.org/105/activity-standard/overview/transactions/
`The value of a transaction can be positive or negative, and contain decimals. It should not contain comma seperators (eg: 3,000)` - it _must_ not contain commas (it is [an extension](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L2845) of [a decimal](https://www.w3.org/TR/xmlschema-2/#decimal-lexical-representation))

http://iatistandard.org/105/activity-standard/overview/transactions/
`A transaction can also include finance-type , flow-type , aid-type and/or tied-status information. [...] A transaction can also contain information on the source and destination organisation. When describing these the provider-org and receiver-org should be used. ` - plus [several other](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/transaction/#subelements) things that are not listed

http://iatistandard.org/105/activity-standard/overview/result/
`Any iati-activity can have either one or multiple result.` - it could also [have zero](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L153)
`A result should have a title and a description to clarify the information being detailed.` - it _[must](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L1848)_ have a title
`Every result should include an indicator,` - it _[must](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L1850)_ include an indicator
`An indicator can have a title and a description` - it _[must](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L1859)_ have a title

**Comment by amy-silcock** [comment]
> http://iatistandard.org/202/activity-standard/overview/budgets/
It is possible to report budget values in multiple currencies - a budget value may be stated only once, and currency is a singular attribute on here, so you cannot state the value in multiple currencies

Budget values can be reported in multiple currencies, providing that each value/currency is in a separate `<budget>` element. Multiple values within a `<budget>` are not allowed.

**Comment by amy-silcock** [comment]
> http://iatistandard.org/105/activity-standard/overview/transactions/
A transaction can also include finance-type , flow-type , aid-type and/or tied-status information. [...] A transaction can also contain information on the source and destination organisation. When describing these the provider-org and receiver-org should be used. - plus several other things that are not listed

Overview guidance is okay. This is not a contradiction that needs changing.

**Comment by amy-silcock** [comment]
@PetyaKangalova this issue is for review. Each commit is shown above, and then the PRs are below.

**Comment by amy-silcock** [comment]
These changes have been implemented
