### ISSUE TITLE
Guidelines - Contradictions with Themselves

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#351]
http://iatistandard.org/202/activity-standard/overview/geography/
This states `When declaring multiple recipient-country or recipient-region then a @pecentage must be declared. These must sum to 100%.` and then later in the page says `It is feasible to have both a recipient-country and recipient-region in the same iati-activity. In such cases, the @percentage must be declared, and sum to 100 across both elements.` The Schema [words it in a different way still](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L336-L338).

http://iatistandard.org/105/activity-standard/overview/transactions/
`Both currency and finance-type , flow-type , aid-type, tied-status can be set as defaults in the iati-activity element` - _both_ indicates there will be two things following. There are 5.

**Comment by amy-silcock** [comment]
@PetyaKangalova this is ready for your review

**Comment by amy-silcock** [comment]
Reference site pages have been updated and new guidance can be found here: https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.03/en/activity-standard/overview/geography.rst
