### ISSUE TITLE
Guidelines - V1 Reference in V2 docs

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#352]
http://iatistandard.org/202/activity-standard/overview/classifications/
`A reporting-org can declare their own @vocabulary, via using the RO (Reporting Org) Vocabulary code.` - this is code `99` in V2. There is nothing under the 2.01 considerations to say this.

**Comment by amy-silcock** [comment]
This issues is now fixed: http://reference.iatistandard.org/203/activity-standard/overview/classifications/
