### ISSUE TITLE
Example 2.0x activity XML could be invalid for country/region mix

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#355]
The [example XML](http://iatistandard.org/202/activity-standard/example-xml/) includes a mix of both ``recipient-country`` and ``recipient-region`` elements

```
  <recipient-country code="AF" percentage="25" />
  <recipient-country code="AG" percentage="25" />  
  <!--recipient-country ends-->
  <!--recipient-region starts-->
  <recipient-region code="489" vocabulary="1" percentage="25" />
  <recipient-region code="289" vocabulary="1" percentage="25" />
  <recipient-region code="A1" vocabulary="99" vocabulary-uri="http://example.com/vocab.html" percentage="100" />
```
However, the written text rule in the schema (for both region and country) says:

> Percentages for all reported countries and regions MUST add up to 100%

Hence, whilst this example tries to show regions from two different vocabularies, it is not in line with this rule, and would fail a test

Suggestion: remove A1 vocabulary example from master example XML file.  Use that XML snippet in isolation, in relevant documentation

@Bjwebb spotted this, when implementing https://github.com/OpenDataServices/cove/issues/871 on CoVE

@andylolz @hayfield @dalepotter thoughts?

**Comment by andylolz** [comment]
> Suggestion: remove A1 vocabulary example from master example XML file

Yep, sounds good to me.

**Comment by stevieflow** [comment]
I think this is still an issue that persists in 2.03 documentation, and we should make efforts to fix

I *think* the issue is a bit wider than described - as the countries adding to 50% look like such in something like d-portal:

![country](https://user-images.githubusercontent.com/1209944/36810965-3312ac16-1cc4-11e8-8496-eafd111c1bd4.png)

This *might* be more to do with d-portal dealing with mixed countries and regions in 2.0x, but I propose we make like simpler for anyone using the sample XML by:

- editing recipient-country elements to add to 100% (75 + 25 for example)
- comment out the recipient-region elements and explain why
- use recipient-region elements in relevant pages

That way, at least if someone downloads and uses the sample XML straight out of the box, they can be secure in what they will get

**Comment by amy-silcock** [comment]
I suggest changing the example to:

```
  <recipient-country code="AF" percentage="25" />
  <recipient-country code="AG" percentage="25" />  
  <!--recipient-country ends-->
  <!--recipient-region starts-->
  <recipient-region code="489" vocabulary="1" percentage="25" />
  <recipient-region code="A1" vocabulary="99" vocabulary-uri="http://example.com/vocab.html" percentage="25" />

```

This provides an example of how all the elements and various vocabularies can be used. How the data would be presented in d-portal is a d-portal issue.

**Comment by andylolz** [comment]
> This provides an example of how all the elements and various vocabularies can be used

Yes absolutely. This is great – this is a better change imo.

> How the data would be presented in d-portal is a d-portal issue.

+1. Did anyone ever report this to the d-portal devs? Does the issue still exist there? Looks like devinit/d-portal#239 is related / could be resurrected for this purpose.

**Comment by amy-silcock** [comment]
D-portal still only shows countries

**Comment by andylolz** [comment]
> D-portal still only shows countries

Cool, thanks for checking. So in that case, I’ll bump devinit/D-Portal#239.

**Comment by amy-silcock** [comment]
This issue is now fixed on the IATI Reference site: http://reference.iatistandard.org/203/activity-standard/example-xml/

**Comment by stevieflow** [comment]
Thanks @amy-silcock
