### ISSUE TITLE
Include budget-not-provided attribute for iati-activity

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Extra-Documentation#361]
Add `@budget-not-provided` to `iati-activity`:

- [ ] Add example to `activity-standard-example-annotated.xml`
- [ ] Create/amend `.rst` file for element
- [ ] Provide usage example
- [ ] Add to changelog
- [ ] Update 2.03 changelog in IATI-Guidance

**Comment by andylolz** [comment]
Linking up issues: this one refs IATI/IATI-Schemas#337.
