### ISSUE TITLE
Add @aggregation-status to indicator element

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Extra-Documentation#366]
Add `@aggregation-status` to `result/indicator`:

- [x] Add example to `activity-standard-example-annotated.xml`
- [x] Create/amend `.rst` file for element
- [x] Provide usage example
- [ ] Add to changelog
- [ ] Update 2.03 changelog in IATI-Guidance

**Comment by dalepotter** [comment]
Closing this in conjunction with the comments in the associated PR: https://github.com/IATI/IATI-Extra-Documentation/pull/379#issuecomment-365660600
