### ISSUE TITLE
Should we replace quotes with double backticks?

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#37]
These are special to reStructuredText, so would look like `this` instead of like "this"

e.g. on https://github.com/IATI/IATI-Extra-Documentation/blob/6a21b5c3c632580cba23341daf40b9e213902b3d/en/iati-activities/iati-activity/result.rst

Follow up from https://github.com/IATI/IATI-Extra-Documentation/issues/36

**Comment by stevieflow** [comment]
Yes
