### ISSUE TITLE
Add @vocabulary for aid-type related elements

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Extra-Documentation#377]
Add `@vocabulary` to `transaction/aid-type`
Add `@vocabulary` to `default-aid-type`

- [x] Add example to `activity-standard-example-annotated.xml`
- [x] Create/amend `.rst` file for element
- [ ] Provide usage example
- [ ] Add to changelog
- [ ] Update 2.03 changelog in IATI-Guidance

**Comment by dalepotter** [comment]
Closing this in conjunction with the comments in the associated PR: https://github.com/IATI/IATI-Extra-Documentation/pull/359#issuecomment-365659482
