### ISSUE TITLE
Add general dates guidance

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#38]
This should clarify whether `YYYY-MM-DD` is the only acceptable format (a tighter restriction than `xs:date`), and whether data consumers should deal with any other formats such as `YYYY-MM-DDZ`.

If the restriction is tighter than that of `xs:date` then there should maybe be a rule in a ruleset to check compliance.

**Comment by stevieflow** [comment]
Think this has to be considered too: https://github.com/IATI/IATI-Extra-Documentation/issues/87

Would propose to push this into "After 1.04" milestone

**Comment by Bjwebb** [comment]
@stevieflow Agreed

**Comment by stevieflow** [comment]
Further to this - we might want to check for 1.04 that ISO 8601 is correct for both:
- `activity-date`: http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/activity-date/
- `generated-datetime` & `lastupdated-datetime` eg: http://dev.iatistandard.org/activities-standard/iati-activities/

The schema text for both these declare use of the `ISO 8601` but in different formats/structures.

@bill-anderson @Bjwebb @caprenter is that acceptable?

**Comment by bill-anderson** [comment]
I think it is important to enforce time in generated-datetime because an audit of when public-facing data is actually updated is important. This must also include include UTC or timezone reference.

lastupdated-datetime doesn't really need the time.

I'm torn on activity-date. A date more fuzzy than yyyy-mm-dd may in some circumstances be more accurate, but it makes users life difficult.

**Comment by Bjwebb** [comment]
Note that in the XML schema `activity-date/@iso-date` is declared as `xs:date`, whereas `@last-updated-datetime` and `generated-datetime` are `xs:dateTime`.

ISO 8601 defines a large number of possible formats for dates, so it is correct to say that both formats are according to ISO 8601, but it's also important to define more precisely what format we mean.

This is the problem described above, where our description of `@iso-date` as being `yyyy-mm-dd` is possibly a slightly narrower constraint than `xs:date`, which can include timezone information. This is a confusion that actually exists between data publishers and data consumers.

So, our documentation could be made clearer, but none of it is actually incorrect - so this is an issue for after the 1.04 release.

**Comment by bill-anderson** [comment]
OK

**Comment by stevieflow** [comment]
Moving this into https://github.com/IATI/IATI-Guidance/issues/38
