### ISSUE TITLE
What characters are permitted/forbidden in identifiers?

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#39]
I've heard it said that identifiers should not contain whitespace - is this said somewhere in the standard documentation?

**Comment by bill-anderson** [comment]
I don't think they should but I'm pretty sure it is not documented. Is this a 2.01 issue? 

iati-identifier and reporting-org/@ref and participating-org/@ref etc must not contain:

space, null, /, \, :

Is this the full list?

**Comment by Bjwebb** [comment]
Depends what are the exact reasons are for restricting these characters. There are all sorts of [odd and unusual](http://en.wikipedia.org/wiki/Control_character#In_ASCII) characters in ASCII, and even more in unicode. Additionally, characters like `#`, `?` and `&` can be especially problematic for URLs if people are not escaping properly. The most surefire way to avoid problems is by using a whitelist and not a blacklist.

If this isn't currently documented anywhere, then I think this is a 2.01 issue.

**Comment by bill-anderson** [comment]
Yes, definitely 2.01
Reason is solely url-related.
Agree with a whitelist. Can you draw one up that we can test against current usage on the dashboard?

**Comment by Bjwebb** [comment]
Thanks. Yes, I'll look into it.

**Comment by stevieflow** [comment]
Have made reference to this in the `iati-identifier` overview pages for both org and activity standards: https://github.com/IATI/IATI-Extra-Documentation/commit/628732f1ee4b39019d4f050dadad201c5aec76cf

**Comment by Bjwebb** [comment]
BTW, I created a whitelist for identifiers, which is now included in the 2.01 proposal: http://support.iatistandard.org/entries/56799133-Version-2-01-Iteration-1-1-Strengthening-the-Core-of-the-Standard

Are there any remaining tasks on this issue?
