### ISSUE TITLE
Advice for publishers about HTTPS

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#41]
Some publishers place their files on servers behind secure certificates. This has caused us, and others, problems in the past for our automated scripts to fetch the data - either due to data consumers using out of dates lists of certificate authorities (CAs), or actual certificate misconfiguration by the publisher.

Currently [IATI-Registry-Refresher](https://github.com/IATI/IATI-Registry-Refresher/) avoids this problem by not verifying HTTPS certificates, but this is not an ideal response. The registry does try to verify, and this has caused problems recently (March 2014).

Updating CA lists is something data consumers can do, but can be quite cumbersome to do. In the case of publisher misconfiguration, this should be fixed by the publisher, but this may be difficult for us to detect and demonstrate to them, because invalid certificates may work in some applications.

We could recommend that publishers don't use HTTPS,  but I'm not sure I'm comfortable
with this, because it provides quite nice identity verification (when it works!).
At the very least we need to tell publishers that this is a potential problem for data consumers.

**Comment by Bjwebb** [comment]
To help quantify the potential problem, it's been suggested that the dashboard should have a list of resources served of HTTPS - https://github.com/IATI/IATI-Dashboard/issues/34

**Comment by Bjwebb** [comment]
For future reference, the publisher that is currently causing problems is BMGF, more information on data.tickets - http://data.tickets.iatistandard.org/ticket/191

**Comment by wendyrogers** [comment]
I have included reference to this advice in the 'Publish Files' section of the new 'How To Publish' guidance

**Comment by Bjwebb** [comment]
https://github.com/IATI/IATI-Guidance/blob/015e531794e31826166df698dd4904264663145c/en/publishing-to-iati/how-to-publish/6-publish-files.rst

> accessible - the URLs are not behind any security protocols/certificates or any other means that would hinder open access (eg https).

I think this line is a bit misleading. Using HTTPS is not a bad thing, it's just that it does seem to have a higher probability of something going wrong.

I plan to add a section about HTTPS to the FAQ, and then modify the above line to be more clear, and like to this longer description. @iatisupport does that sound okay?

**Comment by wendyrogers** [comment]
Have changed the statement to a more general 'the URLs are not behind any security measures or any other means that would hinder open access' for the moment and happy with proposal. Thx

**Comment by avanderpluijm** [comment]
Are there any downsides for wget --no-check-certificate besides unchecked certificates? If you are not interested in SSL in the first place, isn't disabling the check sufficient?

**Comment by Bjwebb** [comment]
@avanderpluijm Yes, `wget --no-check-certificate` is basically sufficient.

We have also had some weird issues with timeouts during the SSL/TLS handshake, which no-check-certificate does not avoid, but for which there are other wget options http://dev.iatistandard.org/developer/tools-generic/#issues

However, whilst wget is the main tool that I use personally, IATI needs to support a wide variety of download agents, not all of which make it as easy to ignore certificates; and, not all developers consider it acceptable to do so.

Additionally, in the case of BMGF - it seems the problem was not out of date CA certificates on the client side, but rather that the site was not sending the intermediary certificate -  http://data.tickets.iatistandard.org/ticket/191#comment:1
The other HTTPS issues I've witnessed personally seemed to be to do with server misconfiguration. Since they're now fixed, I can't debug them further.

**Comment by Bjwebb** [comment]
I've added a new page to the developer docs for this information - http://dev.iatistandard.org/developer/access/ - and linked to it from "Publish Your Datafiles".
