### ISSUE TITLE
Content missing in 2.03 guidance

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#429]
In 2.03, it seems the following are not in the extra-docs, and so not in the live documentation site:

- What do I need to publish? https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.02/en/activity-standard/overview/what-to-publish.rst
- Full list of top-level elements in IATI - https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.02/en/activity-standard/overview/all-elements-in-IATI.rst

**Comment by amy-silcock** [comment]
Thanks for highlighting Steven. I've created the pull requests to create these: https://github.com/IATI/IATI-Extra-Documentation/pulls

**Comment by amy-silcock** [comment]
These pages are now included on the website:
https://iatistandard.org/en/guidance/preparing-data/what-data-to-publish/
https://iatistandard.org/en/guidance/preparing-data/activity-information/activity-information-you-can-publish/
