### ISSUE TITLE
Replace getting started with new section(s)

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#43]
Wendy has started work on this at https://github.com/IATI/IATI-Extra-Documentation/tree/wendy-getting-started

**Comment by wendyrogers** [comment]
I have reviewed the copy for the following sections to make sure the content is covered in the new Guidance material 'How To Publish' or other documentation.
- Getting Started
- What Is IATI
- Policy Considerations
- Managing Implementations
- Data Considerations
- Technical issues
- Preparing Data
- Licensing
- Publishing Data

More information is available in the IATIstandard.org tab of https://docs.google.com/spreadsheet/ccc?key=0An2cSl_hOcDjdDY1MVlqRkNOcGZRaFlWTG9veHJsV2c&usp=drive_web#gid=3

However, the following sections relate to data elements and so need to be located elsewhere within the SSOT?
- Formatting Data
- Financial
- Geopolitical Information
- Identifiers
- Classifications
- Related Documents

**Comment by stevieflow** [comment]
Thanks @iatisupport 

Ill take a look at these in the next pass of the overview sections

**Comment by stevieflow** [comment]
Closing - and creating new Issue : https://github.com/IATI/IATI-Extra-Documentation/issues/122
