### ISSUE TITLE
Contact info overview references final release of v2.01

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Extra-Documentation#439]
[The contact info overview page](http://iatistandard.org/203/activity-standard/overview/contact-info/) says:
> *Please note: these overview pages are currently being updated for the [final release of version 2.01 of the IATI standard](https://github.com/IATI/IATI-Extra-Documentation/milestones/2.01%20Release%20Date) *.

This isn’t correct, and should be removed.

**Comment by amy-silcock** [comment]
I've created the pull requests for 2.02 and 2.01 
https://github.com/IATI/IATI-Extra-Documentation/pull/444
https://github.com/IATI/IATI-Extra-Documentation/pull/443

**Comment by andylolz** [comment]
> I've created the pull requests for 2.02 and 2.01

Great! Thanks!

In general, I’m more than happy to send PRs to all branches – I’d just rather wait until the first one is approved before doing the rest (because if it’s not approved or changes are requested, it creates a bunch of noise for you guys and it’s more difficult to resolve).

Btw in this case, it’s possible to automate sending all the PRs using [`git cherry-pick`](https://git-scm.com/docs/git-cherry-pick) and [`hub`](https://hub.github.com/).

**Comment by dalepotter** [comment]
Just to confirm PR #444 covers `version-2.01` and #443 covers `version-2.02` so we would need a PR for `version-2.03` as well.
