### ISSUE TITLE
Organisation documentation needs adding

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#44]
The text from http://iatistandard.org/organisation-standard/ (and subpages) needs adding to this repository.

**Comment by stevieflow** [comment]
- [x] iati-organisations
- [x] iati-organisation
- [x] name
- [x] reporting-org
- [x] total-budget
- [x] recipient-org-budget
- [x] recipient-country-budget
- [x] document-link

**Comment by stevieflow** [comment]
All done in: https://github.com/IATI/IATI-Extra-Documentation/tree/organisation-standard

Relevant followup Issues created where appropriate

**Comment by Bjwebb** [comment]
If that branch's ready to be merged, could you create a pull request for it?

**Comment by stevieflow** [comment]
https://github.com/IATI/IATI-Extra-Documentation/pull/70
