### ISSUE TITLE
“Previous versions of the IATI Schema” doesn’t include v2.0x

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Extra-Documentation#446]
For v2.02 and v2.03, [the Schema page](http://iatistandard.org/203/schema/#previous-schemas) says:

> Previous versions of the IATI Schema are available:
>   * Version 1.05 of IATI Standard
>   * […]

It doesn’t include include any v2.0x versions.

**Comment by amy-silcock** [comment]
This has been fixed: http://reference.iatistandard.org/203/schema/#previous-schemas

**Comment by andylolz** [comment]
So it has! Thanks
