### ISSUE TITLE
Distinction between embedded and non-embedded codelists is unclear in the docs

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Extra-Documentation#464]
The [IATI Codelist Management page](http://iatistandard.org/203/codelists/codelist-management/) says:

> ### Embedded Codelists
> These are ‘functional’ codelists that are core to IATI. […]

…and…

> ### Non-Embedded Codelists
> These ‘non-functional’ codelists usually provide lookup information on e.g. currencies, languages in use, countries, etc. […]

With changes made in v2.03 (IATI/IATI-Codelists#114) to migrate lots of codelists from embedded to non-embedded, it’s clear that these ‘functional’ and ‘non-functional’ descriptions are no longer sufficient to capture the difference between embedded and non-embedded.

**Comment by Ocre42** [comment]
Considering the codelist management update has been deployed, could we consider this issue as solved? @andylolz

**Comment by andylolz** [comment]
Not sure… I don’t really know much about the codelist management update. Is there an issue or discuss post explaining the plan?

It seems as though the plan was to get away from the old terminology ("embedded" and "non-embedded") and replace it with new terminology ("core", "replicated" etc). I can see that the terms "embedded" and "non-embedded" are still in use, though, so I’m not sure if this is resolved yet.

**Comment by akmiller01** [comment]
I think this "functional" and "non-functional" language has been removed on the modern version of the codelist-management docs: https://iatistandard.org/en/iati-standard/upgrades/how-we-manage-the-standard/codelist-management/

It's since been replaced with "Core, Non-Core, Replicated, and External" so I think we can consider this resolved.
