### ISSUE TITLE
Example XML isn’t valid (incorrect codelist values)

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Extra-Documentation#465]
@stevieflow has spotted the following in [the example XML](http://iatistandard.org/203/activity-standard/example-xml/):

https://github.com/IATI/IATI-Extra-Documentation/blob/eceb2d2aefb085b5ca979fa9e7822ea6ea1971f8/en/activity-standard/activity-standard-example-annotated.xml#L342-L344

The `result/reference/@vocabulary`s here use values that are not included on the [Result Vocabulary](http://iatistandard.org/203/codelists/ResultVocabulary/) codelist. Since the codelist is `complete="1"`, this is invalid.

**Comment by stevieflow** [comment]
Thanks @andylolz 

The examples on http://iatistandard.org/203/activity-standard/iati-activities/iati-activity/result/reference/ also cite vocabs that are not 99, so that needs to be updated

**Comment by andylolz** [comment]
> The examples on http://iatistandard.org/203/activity-standard/iati-activities/iati-activity/result/reference/ also cite vocabs that are not 99, so that needs to be updated

Good point – though those should auto-update when the example XML is fixed (since they come from the same place).

**Comment by stevieflow** [comment]
> though those should auto-update when the example XML is fixed (since they come from the same place).

I'm not so sure, as the first single example is with a vocab of 1 - and includes the text:

> This example declares use of @vocabulary 1, with a @code of 3429:

**Comment by andylolz** [comment]
Ahh, you’re absolutely right @stevieflow! My mistake.

**Comment by stevieflow** [comment]
PR: https://github.com/IATI/IATI-Extra-Documentation/pull/466

**Comment by stevieflow** [comment]
Should the example XML be used as is - this is how it will now look in d-portal: https://github.com/devinit/D-Portal/issues/443#issuecomment-372442512

**Comment by amy-silcock** [comment]
Examples of the reference element are now shown correctly on the website: http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/result/reference/

**Comment by andylolz** [comment]
Great – thanks everyone!
