### ISSUE TITLE
Deploy country budget alignment guidance

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Extra-Documentation#489]
At time of writing, this link doesn’t work:
http://iatistandard.org/203/activity-standard/overview/country-budget-alignment/

This issue replaces #481, which has now been merged.

More details about the guidance itself here:
https://discuss.iatistandard.org/t/guidance-on-implementing-aid-and-budget-alignment/831

**Comment by amy-silcock** [comment]
As the link above is now working and the guidance is on the page I am closing this issue.
