### ISSUE TITLE
conditions/@attached

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#5]
This is a boolean code (what are the others) - but our documentation is not clear as to whether we expect 1/0 true/false etc - and whether this should also be a "codelist".

Needs review/refinement in documentation

**Comment by Bjwebb** [comment]
I'll generate a report of what values people are using for this and other booleans.

**Comment by Bjwebb** [comment]
Here are the different values currently being used for booleans - http://bjwebb.github.io/IATI-Dashboard/booleans.html
`1`,`0`,`true` and `false` are valid values for `xs:boolean` - `True` and `False` are not, they will cause the relevant files to fail schema validation.

**Comment by stevieflow** [comment]
OK thanks - I can pick this up with publishers now.
