### ISSUE TITLE
Codelist management template updates

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/IATI-Extra-Documentation#538]
As part of the management update, a few templates must be updated to match the new definitions, mostly renaming and restructuring links and a few elements in the following templates:

 * [x] https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.03/en/codelists.rst
 * [x] https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.03/en/codelists-guides/codelist-api.rst
 * [x] https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.03/en/codelists-guides/codelist-management.rst

**Comment by Ocre42** [comment]
Solved
