### ISSUE TITLE
Clarify whether an activity can be published in more than one file

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#54]

**Comment by Bjwebb** [comment]
This is clarified in this 2.01 proposal:
http://support.iatistandard.org/entries/41097918-Modify-iati-identifier-validation-and-guidance

> It MUST be globally unique among all activities published by a single reporting organisation

**Comment by Bjwebb** [comment]
This issue is also related https://github.com/IATI/IATI-Extra-Documentation/issues/45

**Comment by stevieflow** [comment]
There should only be one `iati-activity` element in the whole IATI dataset with a given `iati-identifier`

**Comment by stevieflow** [comment]
This is done in: https://github.com/IATI/IATI-Extra-Documentation/commit/c00a6796cce1ce0cfb0033efcdc0a9c6c84d9d31

**Comment by stevieflow** [comment]
Also added: https://github.com/IATI/IATI-Extra-Documentation/commit/7fb7980b66c9b28dc36c507e3fa671ad8a74d7e0

> Across a set of _activity files_ published by a single organisation, individual `iati-activity`, referenced via a unique `iati-identifier`, should not be duplicated.
