### ISSUE TITLE
IATI contains non-ODA

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#55]
Be more explicit about this in our guidance.

IATI has the flow-type, which publishers should use to declare whether their aid is AID or some other type of flow. http://iatistandard.org/codelists/flow_type/

However not all transactions have a flow type. When I have generated stats, I have assumed that those without an explicit flow type are flow type 10 (ODA).

**Comment by wendyrogers** [comment]
I have added a section to the 'Establish Publishing Policies' of the 'How To Publish' guidance that states that aid other than ODA can and should be reported on.
