### ISSUE TITLE
Add examples of  good real data

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#56]
This was suggested at the TAG.

Could either be publishers, or individual files.

**Comment by stevieflow** [comment]
As in the "code examples"

Or - via links to the dashboard?

Or somewhere in between?

**Comment by Bjwebb** [comment]
I think the idea was links to XML files, or at least full quoted activities.

**Comment by stevieflow** [comment]
I have the sample XML with "dummy" data for the time being.  It can be difficult to link to actual XML, as this may a) change b) not always be appropriate

Also - there was another issue to "removing namedropping" from examples

But, this is a good suggestion for Future - and therefore pegging to a post-1.04 milestone for now

**Comment by Bjwebb** [comment]
Yes, that makes sense. I'm aware of the conflict with removing namedropping (https://github.com/IATI/IATI-Extra-Documentation/issues/1), but I thought it was useful to make a note of this suggestion anyway. Perhaps the standard documentation is not the place to do this, but instead some sort of "Featured Data" section on the registry/data page.

Agree with assigning this to Future for now.

**Comment by amy-silcock** [comment]
No further discussion has happened. Example of xml can be found here: http://reference.iatistandard.org/203/activity-standard/example-xml/
