### ISSUE TITLE
BUG: `document-link/category` can occur multiple times

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Extra-Documentation#575]
The [related documents guidance](https://drive.google.com/file/d/1TI9PU5dyyRE2IzervFPUZz_Xfue16xYC/view?usp=sharing) says:

![Screenshot 2019-09-23 at 21 05 50](https://user-images.githubusercontent.com/464193/65494796-695e3180-dead-11e9-9c95-d48e5a77749d.png)

[According to the schema](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/document-link/category/#rules), `category` must occur **at least once** (not only once). There’s no upper bound on the number of times it can occur.

**Comment by andylolz** [comment]
This guidance notably contradicts Aid Transparency Index guidance, which actively encourages publishers to tag `document-link`s with all applicable categories.

**Comment by amy-silcock** [comment]
Hi Andy,

The schema says a category code must be included once and only once for each category element. The actual category element must be included once or multiple times.

**Comment by amy-silcock** [comment]
Thanks Andy, I'll get this changed

**Comment by andylolz** [comment]
Great – thanks.

Are the guidance PDFs (e.g. [the one in this ticket](https://drive.google.com/file/d/1TI9PU5dyyRE2IzervFPUZz_Xfue16xYC/view?usp=sharing)) defunct now? Maybe they should be removed from google drive, or ideally redirected.

**Comment by amy-silcock** [comment]
Hi Andy, yes they should be archived. They're now all managed and kept up to date via GitHub.

**Comment by amy-silcock** [comment]
Just checked with the team, we have no control over the Google webservers so we wouldn't be able to implement redirects :(

**Comment by andylolz** [comment]
There are a couple of options:

 * **To redirect**, replace the contents of the PDFs with a link that says "[This guidance has moved to a new location.](https://iatistandard.org/en/guidance/standard-guidance/related-documents/)"
 * **To remove completely**, permanently delete the PDFs from Drive (by deleting, and then emptying the bin)

**Comment by andylolz** [comment]
> To redirect, replace the contents of the PDFs with a link that says "[This guidance has moved to a new location.](https://iatistandard.org/en/guidance/standard-guidance/related-documents/)"

^^ I think this would still be worthwhile. It’s not an ideal redirect, but it does the job. Just as an example of these PDFs being used in the wild, it looks as though the new validator is pointing to these PDFs, in its "see guidance" links.

Given it’s not always predictable where they’ve been linked from, it would be good practice to signpost users to the correct location, for posterity.

**Comment by PetyaKangalova** [comment]
@andylolz thanks for the suggestion. Just to update that for the validator we will be replacing the PDF links with the the new pages in the next few weeks.

For the permanent suggestion you made, I'll share with the team. It is not on our priority at the moment, but will keep you posted.
