### ISSUE TITLE
Code List vs Codelist is inconsistent

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#60]

**Comment by stevieflow** [comment]
Which one to use?

**Comment by Bjwebb** [comment]
I prefer codelist, but I don't really mind.

**Comment by stevieflow** [comment]
@caprenter any preference?

**Comment by stevieflow** [comment]
Would / could you find and replace Code List etc for codelist?

**Comment by Bjwebb** [comment]
Okay, will do.
