### ISSUE TITLE
Org standard - document-link - recipient-country mismatch on ordering between code example and navigation/standard summary table

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#618]
I noticed in https://github.com/OpenDataServices/cove/issues/1366 that the ordering of the elements in the code example for document-link/recipient-country do not match the order of the navigation and standard summary table

![document-link-iatistandard-org (1)](https://user-images.githubusercontent.com/1209944/147930339-aac35de3-0f84-4f72-99f6-1c1ffdd2e1a6.png)
![Organisation-Standard-Summary-Table-iatistandard-org](https://user-images.githubusercontent.com/1209944/147930341-d6002204-681d-4afa-8600-bfe4d0f3c705.png)
![document-link-iatistandard-org](https://user-images.githubusercontent.com/1209944/147930343-9dcfb2b9-9ad0-4043-9c0e-29aefbd6ce57.png)

I believe the document-link/recipient-country has to be the _last_ sub-element, as the schema considers this as some kind of extension to the documentLinkBase (in common.xsd) - in iati-organisations-schema.xsd:

> documentLinkWithReceipientCountry extends documentLinkBase to include the receipient-country sub-element, which is used within the iati-organisations schema 

Hence, I think the ordering of the website navigation and the standard summary table need to be adjusted, to avoid any ambiguity... I think!

**Comment by amy-silcock** [comment]
Hi Steven, good spot!

As mentioned the code example and IATI Validator expect the <recipient-country> element to be the last child element under `<document-link>` in an org file. Checked by adding a <document-link> element into UNHCR's org file.

Code example: https://iatistandard.org/en/iati-standard/203/organisation-standard/iati-organisations/iati-organisation/document-link/recipient-country/

@IATI/devs, link to the two schemas are:
Org Schema with recipient-country complex type: https://github.com/IATI/IATI-Schemas/blob/5e53af3730d36ecc125dd738e435c3d682c0f3b8/iati-organisations-schema.xsd

Common schema with document-link: https://github.com/IATI/IATI-Schemas/blob/5e53af3730d36ecc125dd738e435c3d682c0f3b8/iati-common.xsd

As Steven mentioned, the organisation summary table and website navigation place the `<recipient-country>` as the first child element under `<document-link>`, it should be the last.

**Comment by stevieflow** [comment]
Thanks @amy-silcock 

I can see that @akmiller01 has logged a ticket for the website ordering, which is great.

I'm not too sure where the standard summary table is managed though (and suspect it was probably me, years ago, who misaligned this!).

**Comment by akmiller01** [comment]
@stevieflow I think the summary table order will be rectified by this pull request: https://github.com/IATI/IATI-Standard-SSOT/pull/388/files

Essentially the SSOT was hardcoded to first check for extension attributes/children, and then base attributes from a complex type. So I swapped those so extensions will always appear after the bases.

**Comment by stevieflow** [comment]
Great - thanks @akmiller01

**Comment by akmiller01** [comment]
These changes should be live now @stevieflow https://iatistandard.org/en/iati-standard/203/organisation-standard/summary-table/

**Comment by stevieflow** [comment]
Confirmed

Amazing - thanks so much @amy-silcock & @akmiller01 

cc/ @Bjwebb
