### ISSUE TITLE
Add guidance of capitilisation

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#63]
E.g. titles that are in all caps can be problematic for data consumers.

**Comment by stevieflow** [comment]
@Bjwebb do you mean freetext elements such as activity/result  `title` & `description` , but then also elements such as contact-info `person-name` or org standard `name`  etc?

Or specifically just activity `title` ?

**Comment by Bjwebb** [comment]
All free text elements really. `title` is just the main element where I've come across it.

**Comment by stevieflow** [comment]
Added to overview pages for `title` `description` `result` `contact-info` and `iati-activity` and `iati-organisation`: 

https://github.com/IATI/IATI-Extra-Documentation/commit/f0051e897204f96275bc3f47aa22b437ea5151ed

https://github.com/IATI/IATI-Extra-Documentation/commit/12e66469bd911c6ad98867b3365e4971e1cd65f1
