### ISSUE TITLE
Implement "5. A consistent approach to organisation identifiers"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#67]
http://support.iatistandard.org/entries/41042267-Modify-DAC-derived-organisation-identifiers
- [x] 1) The OECD DAC is recognised as a registration agency with code XM-DAC.
- [ ] 2) DAC donor codes should be adopted 
- [ ] 3) DAC agency codes should be modified to be consistent with donor codes
- [ ] 4) DAC delivery channel codes should be prefixed with the DAC agency code.
- [ ] Additionally: IATI will put in place a cross-referencing utility to ease the pain for users of data.

**Comment by Bjwebb** [comment]
1) has already been done
https://github.com/IATI/IATI-Codelists-NonEmbedded/blob/0730c5c808b8b9ec29093796e0f2c5a403db727f/xml/OrganisationRegistrationAgency.xml#L317
http://dev.iatistandard.org/201/codelists/OrganisationRegistrationAgency/

2) 3) and 4) require no changes to any machine readable part of the standard, which is why this issue is reported against the human readable Documentation.

**Comment by caprenter** [comment]
@bill-anderson As we stand this whole issue needs some clarification as to the actions we actually need to take in the light of community feedback on the proposal. Therefore assigning this issue to you for now.

**Comment by stevieflow** [comment]
The latest proposal is here: http://support.iatistandard.org/entries/52824355-Version-2-01-Iteration-3-9-Organisation-and-Activity-Identifiers

**Comment by bill-anderson** [comment]
Discuss this morning. Issues are
- other-identifier
- XI-IATI codelist
- Guidance words

**Comment by bill-anderson** [comment]
Forum is revised

**Comment by caprenter** [comment]
Assigned to @stevieflow to see where this needs to be done.
We have some good information in the migration document.
The XI-IATI codelist is being worked on via email and https://github.com/IATI/IATI-Schemas/issues/231
other-identifier is in the schema

Where else does this need to be documented?

**Comment by stevieflow** [comment]
It will need to go into update overview pages - Ill label it so

**Comment by stevieflow** [comment]
This may also be a linked task: https://github.com/IATI/IATI-Extra-Documentation/issues/278

**Comment by stevieflow** [comment]
moved to https://github.com/IATI/IATI-Guidance/issues/191
