### ISSUE TITLE
Usage & compliance missing from new organisation standard documentation

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#73]
E.g.
http://iatistandard.org/organisation-standard/documents/
http://dev.iatistandard.org/organisation-standard/iati-organisations/iati-organisation/document-link/

This should maybe be captured in the Extra-Documentation text, or possibly in a Ruleset.

**Comment by caprenter** [comment]
Well spotted - this is also available in previous web versions of the standard.

Seems to me the tasks are to audit the information (is it still correct?) and then yes, rulesets and or extra documentation seems sensible.

**Comment by stevieflow** [comment]
FYI

I have started to put this into overview pages.

Some of it is also inherent in the schema

But agree - needs to be audited and structured

**Comment by Bjwebb** [comment]
Some of it is inherent in the schema, but not anything about elements being mandatory. That's what Rulesets are for.

**Comment by stevieflow** [comment]
With the overview pages , some of this is now covered, but an Org ruleset is not

Suggest to push this to Post 1.04 - we also need to think about a Ruleset "section"?

**Comment by bill-anderson** [comment]
I'm happy for this to go post 1.04

**Comment by stevieflow** [comment]
@Bjwebb do we need a dedicated milestone to collect issues around documenting Rulesets, perhaps?

**Comment by Bjwebb** [comment]
@stevieflow Yes, that seems like a good idea.

**Comment by stevieflow** [comment]
Im wary that https://github.com/IATI/IATI-Extra-Documentation/pull/207 may still not cover this original issue...

**Comment by Bjwebb** [comment]
Yes, I think that's probably correct. This original issue is about information from the 1.03 organisation documentation not being preserved in the 1.04 documentation. As far as I can tell this is still the case.

**Comment by stevieflow** [comment]
Is this more about usage "0....1" type rules?

**Comment by Bjwebb** [comment]
Yes.

**Comment by akmiller01** [comment]
Probably covered by https://iatistandard.org/en/iati-standard/203/organisation-standard/summary-table/
