### ISSUE TITLE
Add Reference section to navigation to hold xml elements

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#74]

**Comment by stevieflow** [comment]
Include Organisation Standard Overview Table in this

Rename Organisation Standard Overview Table navigation to Overview Table

**Comment by Bjwebb** [comment]
Include the Overview Table in the Reference section, and not the Overview section?

**Comment by stevieflow** [comment]
Good point

As the first item in the Reference section perhaps?

Only issue is that it is labelled Overview and _not_ in the Overview section!

**Comment by Bjwebb** [comment]
We could call it a Summary Table, instead of an Overview Table...

**Comment by stevieflow** [comment]
Nice.  I can see what you've done there
