### ISSUE TITLE
Reduce indentation in code examples

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#78]
(to make them fit more nicely on the page)

e.g. http://dev.iatistandard.org/organisation-standard/overview/example-xml/

**Comment by Bjwebb** [comment]
@stevieflow is doing this as part of his work of including the XML from an external file https://github.com/IATI/IATI-Extra-Documentation/issues/89

**Comment by stevieflow** [comment]
Done: https://github.com/IATI/IATI-Extra-Documentation/commit/fb632a05286a271e9e9e4ebf24bda105be676dd6
