### ISSUE TITLE
Activities or Activity Standard?

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#79]
In a similar vein to other observations, just want to clarify if using plural or singular is the default.

Some publishers only publish one activity...

**Comment by Bjwebb** [comment]
And some publishers publish more than one organisation, but with call it the Organisation Standard.

**Comment by stevieflow** [comment]
If we use Activity Standard then

http://dev.iatistandard.org/activities-standard/ will need updating (page title and file name)

**Comment by Bjwebb** [comment]
There are redirects from both http://iatistandard.org/activity-docs/ and http://iatistandard.org/activity-standard/ to http://iatistandard.org/activities-standard/ - does anyone know if the Activiti(y|ies) standard pages used to be at those urls, and why if so why it was changed to "activities"?

**Comment by stevieflow** [comment]
Looks like it has always been activities-standard:

http://iatistandard.org/101/activities-standard/

But - think we should now be consistent and use activity-standard for 1.04 and onwards

@bill-anderson - is this acceptable?

**Comment by stevieflow** [comment]
Also - noticed that the file name for the xsd is using plural: 

http://iatistandard.org/schema/

**Comment by Bjwebb** [comment]
Yes, for both activities and organisations. Whereas http://dev.iatistandard.org/organisation-standard/ describes it as a "organisational standard"!

**Comment by bill-anderson** [comment]
Sorry for not intervening earlier. Are we agreed on Activities and Organisation for descriptions, leaving xml as is.

**Comment by stevieflow** [comment]
I propose Activity standard, as it is same unit as Organisation.  It just so happens that you can publish multiple, but you can (and many do) report one Acivity/Organisation

**Comment by bill-anderson** [comment]
I'm happy with that if it is not too disruptive with changing urls

**Comment by Bjwebb** [comment]
It's a nice easy one to add a redirect for, so url related disruption should be minimal.
