### ISSUE TITLE
Be explicit that document-link/@url should be the actual url of the document

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#81]
A web address where the document can be downloaded can be declared through the url attribute.

http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/document-link/
http://dev.iatistandard.org/organisation-standard/iati-organisations/iati-organisation/document-link/

I feel that this is particularly ambiguous:  

> A web address where the document can be downloaded can be declared through the url attribute:

**Comment by stevieflow** [comment]
Are the code-examples in http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/document-link/ any better ?

**Comment by Bjwebb** [comment]
Yes, that looks good.
