### ISSUE TITLE
Rewrite text from codelists paper for website

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#82]
https://docs.google.com/document/d/1oeH-8BFB__2IYF4MLnUwx2LcXZCVd5e-iYsXtQ4ViTk/edit#heading=h.oxgl16fpzq83

**Comment by stevieflow** [comment]
Where would this sit?

**Comment by Bjwebb** [comment]
Good question.

I think it belongs in the codelists section. Either in the front page, or in another page pinned to the top of the navigation (in the same way that "Codelist API") currently is. http://dev.iatistandard.org/codelists/

**Comment by stevieflow** [comment]
Or - a section "managing the standard", which could be within Updates, or associated with it (or just a section of it!)

There could be similar "policy" type documents that relate to technical decisions

**Comment by Bjwebb** [comment]
Yes, that's also a possibility. I said codelists section because I think it is important that information such as Embedded vs. Non-Embedded is mentioned there. However, it could be a short mention that links to somewhere else, such as "managing the standard"

**Comment by stevieflow** [comment]
Yes

We could edit the text here to cover that possibility: http://dev.iatistandard.org/codelists/ - maybe also have an "overview" page within codelists section?

**Comment by caprenter** [comment]
Draft text on codelist management here to those that have permission to access:
https://docs.google.com/document/d/16u6z8g6Yo1P7mhljogjMr3bLFsD46kseLQFUlsQaUX4/edit#

**Comment by caprenter** [comment]
Text agreed.
@Bjwebb to put into the SSOT.
