### ISSUE TITLE
Linked documents format description

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#83]
@stevieflow 

On http://dev.iatistandard.org/activities-standard/overview/linked-documents/ you have written:

> Although many different kinds of format can be presented, it is recommended to utilise the ones represented in the FileFormat codelist

I don't think this is correct now that all IANA media types are on the codelist. The code must be on the codelist

**Comment by stevieflow** [comment]
ok: https://github.com/IATI/IATI-Extra-Documentation/commit/01531b334504d34ad688e5b8c8530aaae24a6b0b
