### ISSUE TITLE
code-examples for iso dates - text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#87]
We should clarify whether date examples for 1.04 should only include the ISO date within the XML 

So the example of:

`<activity-date iso-date="2012-04-15" type="start-planned">2012-04-15</activity-date>`

could be:

`<activity-date iso-date="2012-04-15" type="start-planned"/>`

Also see: https://github.com/IATI/IATI-Extra-Documentation/issues/38

**Comment by Bjwebb** [comment]
I don't think it matters much which of the above publishers use. However, I think the latter is what we should be suggesting in our examples.

**Comment by stevieflow** [comment]
If @caprenter agrees, I can easily update all code-examples accordingly

**Comment by bill-anderson** [comment]
@caprenter and I discussed the text part earlier and we agreed that there are cases where this is important. There might be a formal written agreement to start an activity in "mid June".

**Comment by Bjwebb** [comment]
Yes, the text part is important, and we should have an example showing how to use this.

However, I don't think that telling publishers to duplicate an iso date in the text part is useful.

**Comment by stevieflow** [comment]
Where do we stand on guidance for `period-start` & `period-end` combinations and text?

eg:

`<period-start iso-date="2015-01-01">2015</period-start>
<period-end iso-date="2015-12-31">2015</period-end>`

Is _2015_ useful in this example?  Could / should it be:

`<period-start iso-date="2015-01-01">Start of financial year 2015</period-start>
<period-end iso-date="2015-12-31">End of financial year 2015</period-end>`

Or 

`<period-start iso-date="2015-01-01"/>
<period-end iso-date="2015-12-31"/>`

for @bill-anderson

**Comment by stevieflow** [comment]
@bill-anderson

**Comment by caprenter** [comment]
I think the current examples for period-start:
http://iatistandard.org/activities-standard/budget/period-start/
and period-end
http://iatistandard.org/activities-standard/budget/period-end

are fine.

The text part should be discouraged, and it should be clear that an ISO date is preferred and importantly, actually of some use to most data consumers (and their machines). In the case where it is not possible to provide an ISO date, but the text may still be of some use to a human, then go ahead and supply it.

I don't see the point of supplying both an ISO date and text.

**Comment by bill-anderson** [comment]
Budgets need iso-dates: this is not standalone information but is essential for analysis of budget values. In the case of budgets text is meaningless as the period is already described.

For activity and transaction dates we need a specific iso-date, but the text can be used to explain that the actual date is more fuzzy than the iso-date

**Comment by stevieflow** [comment]
@bill-anderson 

From this discussion, I understand that:
- [x] `budgets` - the `period-start` and `period-end` date examples should just be iso-dates, as the text is meaningless.  Therefore, the example-code needs to be updated: https://github.com/IATI/IATI-Extra-Documentation/commit/b8e24326c1e275c368074e924eb2ed353af42e48
- [x]  `transactions` - text might be needed to add clarification.  However, would the `description` element not be suffice for this (as many publishers do)? https://github.com/IATI/IATI-Extra-Documentation/commit/f6aacdac732355175c453d1629f92fa6daf07307
- [x]  `activity-date` - we should adjust the code-example to include dates with text : https://github.com/IATI/IATI-Extra-Documentation/commit/3ffa75ded8ef9b1df5e38817f1e89e87813a0864

**Comment by bill-anderson** [comment]
I agree on budgets and activity

Transactions I sort of agree. But don't feel strongly either way.

**Comment by stevieflow** [comment]
@bill-anderson thanks

Just to clarify - is it `activity-date` you dont feel strongly about?

**Comment by bill-anderson** [comment]
Oops. No transactions

**Comment by stevieflow** [comment]
ok

**Comment by stevieflow** [comment]
I've adjusted the code examples accordingly, and made a pull reqest: https://github.com/IATI/IATI-Extra-Documentation/issues/159

**Comment by stevieflow** [comment]
I've also added free text for a code-example for `planned-disbursement`: https://github.com/IATI/IATI-Extra-Documentation/issues/87#ref-commit-701e10d
