### ISSUE TITLE
Activity file should have iati-activities as the root element

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Extra-Documentation#88]
This should be mentioned on:
http://dev.iatistandard.org/activities-standard/overview/activity-file/

Similarly, an Organisation File should have a root element of iati-organisations, even if it describes only one organisation.
http://dev.iatistandard.org/organisation-standard/overview/organisation-file/

**Comment by stevieflow** [comment]
Done: https://github.com/IATI/IATI-Extra-Documentation/commit/56d6b950e9901765954bf40f3e4f91cbe3be7220
