### ISSUE TITLE
Using bullets in example-code

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#99]
Review whether Example Usage statements should use bullet points

**Comment by stevieflow** [comment]
No

**Comment by Bjwebb** [comment]
![](http://img2.wikia.nocookie.net/__cb20130709214607/lego/images/c/c3/39215-grumpy-cat-no-Rwoe.jpeg)

**Comment by stevieflow** [comment]
Exactly
